Add AST: OCaml + Recursive values (Viacheslav Sidorov and Danila Rudnev-Stepanyan)
Kakadu/fp2024 pull request #10
Opened 2024-09-29 16:42 UTC by xamelllion

`lib/ast.ml` - реализация дерева абстрактного синтаксиса
`bin/main.ml` - пример AST функции факториал

2024-09-29 18:07 UTC, therain7 requested changes

2024-09-29 18:07 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +  | ExprIf of expression * expression * expression (* if expr1 then expr2 else expr3 *)
`if x then y` не представимо

2024-09-29 18:07 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +  | ExprLet of rec_flag * binding * expression (* let x = expr1 in expr2 *)
Взаимно рекурсивные определения не представимы

2024-09-29 18:07 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +  | ExprFun of identifier (* fun p -> e *)
А тело куда? И где потерялись паттерны?

2024-09-29 18:07 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +      * expression list (* let `rec` f a b = [ some_expressions ] *)
Представимо некорректное
`let x = 1 in let y = 2`

2024-10-01 20:41 UTC, xamelllion commented on OcamlRV/dune-project
> +(authors "Viacheslav Sidorov, Danila Rudnev-Stepanyan")
Поправил

2024-10-01 20:41 UTC, xamelllion commented on OcamlRV/dune-project
> +  "")
Добавил

2024-10-01 20:41 UTC, xamelllion commented on OcamlRV/lib/ast.ml
> +  | ExprIf of expression * expression * expression (* if expr1 then expr2 else expr3 *)
Вроде поправил

2024-10-01 20:41 UTC, xamelllion commented on OcamlRV/lib/ast.ml
> +  | ExprFun of identifier (* fun p -> e *)
Поправил

2024-10-01 20:43 UTC, xamelllion commented on OcamlRV/lib/ast.ml
> +      * expression list (* let `rec` f a b = [ some_expressions ] *)
Убрал эту конструкцию, вместо неё ExprLet

2024-10-02 18:09 UTC, therain7 requested changes

2024-10-02 18:09 UTC, therain7 commented on OcamlRV/dune-project
> +(maintainers "Viacheslav Sidorov me@xamelllion.ru" "Danila Rudnev-Stepanyan dabzelos@gmail.com")
Почта обычно пишется в `<>`. Типа того, что вы видите в `git log`

2024-10-02 18:09 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +[@@deriving show { with_path = false }]
```suggestion
```

2024-10-02 18:09 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +  | Eq (* = *)
Используйте doc комменты `(** some docs *)`

2024-10-02 18:09 UTC, therain7 commented on OcamlRV/lib/ast.ml
> +  | ExprLet of rec_flag * pattern list * expression list (* let x = expr1 in expr2 *)
В теории у вас представимо некорректное
```ocaml
let x = 1 in let y = 2
```
И объясните, что вы подразумеваете под `expression list`?
Что если список будет содержать 3 элемента?

2024-10-06 14:26 UTC, xamelllion commented on OcamlRV/lib/ast.ml
> +  | ExprLet of rec_flag * pattern list * expression list (* let x = expr1 in expr2 *)
Собственно я наконец то разобрался как оно должно выглядеть, и понял что глобальные функции вида expression не лучшая идея и добавил тип structure_item

2024-10-06 19:49 UTC, therain7 approved these changes
norm

2024-10-06 19:49 UTC, merged