Add AST: OCaml + ADT (Mikhail Gavrilenko, Rodion Suvorov)
Kakadu/fp2024 pull request #11
Opened 2024-09-29 18:44 UTC by suvorovrain

- `lib/ast.ml` - AST
- `lib/main.ml` - Factorial example

2024-09-29 19:25 UTC, therain7 requested changes

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/dune-project
> +(authors "Rodion Suvorov Mikhail Gavrilenko")
```suggestion
(authors "Rodion Suvorov <почта сюда>" "Mikhail Gavrilenko <почта сюда>")
```

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/dune-project
> +(homepage "https://github.com/suvorovrain/OcamlADT")
А PR делаете из другого репозитория 0_0

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +  (** Expressions [E0, E1, (E2, ..., En)] *)
В комментарии что-то странное.
Предполагается, что вы синтаксис n-ок покажете, а не AST представление

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +  (** [Exp_function ([P1; ...; Pn])] represents
А с tuple вы инвариант поддерживаете в типе, а не просто комментом

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +     [fun P1 ... Pn -> E]
У вас `C` в `E` переименовалось :)

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +      represents a product type [T1 * T2]. *)
Посмотрите на типы следующих выражений:
```
(1, 2, 3)
((1, 2), 3)
(1, (2, 3))
```

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/dune
> +;  (deps ./REPL.exe %{bin:REPL}))
Предлагаю это удалить

2024-09-29 19:25 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +[@@deriving eq, show { with_path = false }]
Оба типа нигде не используются

2024-09-29 19:30 UTC, suvorovrain commented
Спасибо Андрей!!!

2024-09-30 15:55 UTC, therain7 requested changes
CI почините

2024-09-30 15:55 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +  | Str_type of ident * (ident * type_expr list) * (ident * type_expr list) list
может быть объявление типа без конструкторов

2024-09-30 15:55 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +  | Exp_match of expression * case list (** [match E0 with P1 -> E1 | ... | Pn -> En] *)
А здесь инвариант? Можете забить и забить тогда везде :)

2024-09-30 15:55 UTC, therain7 commented on OcamlADT/dune-project
> +(maintainers "Rodion Suvorov Mikhail Gavrilenko")
здесь как выше

2024-10-01 13:12 UTC, therain7 approved these changes

2024-10-01 13:17 UTC, merged