Add ast library
Kakadu/fp2024 pull request #12
Opened 2024-09-29 21:28 UTC by kar1mgh

**Added**:

- library for abstract syntax tree in ```lib/ast/ast.ml```

- example for factorial function in ```bin/astExample.ml```

To run test that prints ast for factorial function run ```dune build @runtest```. The output will be in ```Go/_build/default/tests/test_ast.t```.

2024-09-30 06:01 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      }] *)
Так разве нельзя?
```go
for i, elem := range some_fun() {
}
```

2024-09-30 06:03 UTC, therain7 requested changes
еще CI почините :)

2024-09-30 19:01 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> Похоже, что справа от `go` и `defer` может быть только `Expr_call`. Попробуйте соответствующее ограничить типы конструкторов

Не обязательно. Есть, например, анонимные горутины, которые после `go` содержат анонимную функцию. То же самое касается и defer, поэтому не вижу смысла здесь что-то менять.

2024-09-30 19:06 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +[@@deriving show { with_path = false }]
> Этот комментарий как-то совсем не помогает разобраться в типе, который он описывает. Перепишите как-нибудь, чтобы было понятно..

В смысле, а что здесь не понятно-то? Описание семантики и базовый пример, разве еще что-то нужно?

2024-09-30 19:09 UTC, therain7 commented on Go/lib/ast/ast.ml
> +[@@deriving show { with_path = false }]
Комментарий совсем не помогает разобраться в этом наборе:
`ident * (ident * type' option) list option * type' list option * stmt`.

Хотелось бы пояснение, раз делаете не рекордом

2024-09-30 19:11 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
Поясните пожалуйста, почему в go-шном AST так
<img width="436" alt="image" src="https://github.com/user-attachments/assets/e9c1761c-9191-4c02-bbd0-e66259dc9ca2">

https://github.com/golang/go/blob/master/src/go/ast/ast.go

2024-10-01 08:43 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> Поясните пожалуйста, почему в go-шном AST так <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/15161335/372214975-e9c1761c-9191-4c02-bbd0-e66259dc9ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MzE3MjEsIm5iZiI6MTcyNzczMTQyMSwicGF0aCI6Ii8xNTE2MTMzNS8zNzIyMTQ5NzUtZTljMTc2MWMtOTE5MS00YzAyLWJiZDAtZTY2MjU5ZGM5Y2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIxMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODhhN2RmMDQzMzEwOWZmOWYyMzYzNWE4ZWRlMWUyN2NlZGFmZmNhZDNkYzY3NjVkZjdmMGUzNmU0OWRjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A-g5FhVM-g1iJw0Llbkt7EE6G9RY4XhKRU3-2GFQFjo">
> 
> https://github.com/golang/go/blob/master/src/go/ast/ast.go

Потому что они FuncLit и обычные вызовы функций различают на этапе парсинга CallExpr, что выглядит несколько странно. Пробежал краем галаза по коду парсера https://github.com/golang/go/blob/master/src/go/parser/parser.go, похоже что они в parseFuncTypeOrLit() пытаются тут же определить функцию и подставить ее вызов. Кажется, что наше решение выглядит дальновиднее, но до парсера мы еще не добрались, поэтому пока нельзя сказать наверняка. Если есть какие-то серьезные голоса "За" решение, подобное предложенному разработчиками языка, будет оченб интересно выслушать, потому что, повторюсь, до парсера мы еще не добрались.

2024-10-01 08:58 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
<img width="540" alt="image" src="https://github.com/user-attachments/assets/67740087-141e-4dd7-8370-46aaaf22f129">
Кажется, вы все-таки просто не правы

2024-10-01 09:13 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/15161335/372393996-6cdbdb95-64e7-48d1-a90b-12703538926e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzM4OTcsIm5iZiI6MTcyNzc3MzU5NywicGF0aCI6Ii8xNTE2MTMzNS8zNzIzOTM5OTYtNmNkYmRiOTUtNjRlNy00OGQxLWE5MGItMTI3MDM1Mzg5MjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA5MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTVlOTAwZTk3MjY3ZWY3MWE3NWU0MTY1Yzg1NTkwNDc4ZGJlYjJjNGIzNDRmMmQ1N2M2N2FlNmQwMjJmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9snZJoWxr4rzl642Ccw0-Vh7kLQSUv9KiLnT36Ozwa4">
> 
> Кажется, вы все-таки просто не правы

Здесь неправильно написана анонимная функция, в конце должен быть ее вызов ()

2024-10-01 09:13 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> > <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/15161335/372393996-6cdbdb95-64e7-48d1-a90b-12703538926e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzM4OTcsIm5iZiI6MTcyNzc3MzU5NywicGF0aCI6Ii8xNTE2MTMzNS8zNzIzOTM5OTYtNmNkYmRiOTUtNjRlNy00OGQxLWE5MGItMTI3MDM1Mzg5MjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA5MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTVlOTAwZTk3MjY3ZWY3MWE3NWU0MTY1Yzg1NTkwNDc4ZGJlYjJjNGIzNDRmMmQ1N2M2N2FlNmQwMjJmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9snZJoWxr4rzl642Ccw0-Vh7kLQSUv9KiLnT36Ozwa4">
> > Кажется, вы все-таки просто не правы
> 
> Здесь неправильно написана анонимная функция, в конце должен быть ее вызов ()

![изображение](https://github.com/user-attachments/assets/ebe65bbd-dc03-4a67-9ecd-351df6ac4353)
например вот так будет работать

2024-10-01 09:14 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
И здесь справа `Expr_call`

2024-10-01 09:17 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> И здесь справа `Expr_call`

Подразумевается что '()' это `ExprCall`?

2024-10-01 09:18 UTC, admitrievtsev commented on Go/lib/ast/ast.ml
> +  | Stmt_go of expr (** Goroutine statement: [go func(ch chan<- bool)] *)
> > И здесь справа `Expr_call`
> 
> Подразумевается что '()' это `ExprCall`?

Да, это вообще так и есть, но сам Functlion Literal нам же тоже нужно учитывать в такой функции

2024-10-01 16:08 UTC, kar1mgh commented on Go/lib/ast/ast.ml
> +  (** An anonymous function such as [func() {}], [func(a int, b int) int { return a + b }] *)
Если добавить сделать имя функции ```ident option``` мы разрешим анонимные функции в ```top_decl```, что не имеет смысла. У меня не получается прочувствовать эту грань, представимость чего ещё можно допускать в аст, а чего нет. Дмитрий Сергеевич говорил, что некорретные программы не должны быть представимы в аст. Но они представимы даже в оригинальном компиляторе го... К некоторым таким вещам претензия есть (например ниже), а к некоторым нет. Почему?

2024-10-01 16:15 UTC, kar1mgh commented on Go/lib/ast/ast.ml
> +      }] *)
Это намек на то, что это не должно быть представимо? Если да, то ведь придется половину всего выносить из ADT, ограничивать как-то, чтобы некорректные программы не были представимы. Или это норм и так и надо?

2024-10-02 17:53 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      }] *)
Меня скорее напрягает наличие `Stmt_empty`. Подскажите, почему по вашему мнению оно действительно необходимо в AST?
Т.к. на первый взгляд оно только создает странные конструкции подобные той, что выше

2024-10-02 18:07 UTC, shakareem commented on Go/lib/ast/ast.ml
> +      }] *)
Идея была в том, что внутри тела функций или ифов может быть пустым, но да, можно сдлеать ```stmt option```

2024-10-02 18:22 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  (** An anonymous function such as [func() {}], [func(a int, b int) int { return a + b }] *)
типа такого?
![image](https://github.com/user-attachments/assets/80ca1490-ce4d-4d29-9970-f55a0643b4a7)
![image](https://github.com/user-attachments/assets/23ea4300-d9aa-4f79-aebf-7093c0b1e0d4)

2024-10-02 18:23 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      }] *)
`option` почти всегда будет лучше, т.к. он будет расставлен точечно, а не везде, где возможен statement в целом

2024-10-02 18:24 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  (** An anonymous function such as [func() {}], [func(a int, b int) int { return a + b }] *)
типа того

2024-10-02 18:48 UTC, therain7 commented
![image](https://github.com/user-attachments/assets/4541e306-9005-4e9c-bdd9-bf147892cb6d)

2024-10-02 18:52 UTC, Kakadu commented on Go/lib/ast/ast.ml
> +[@@deriving show { with_path = false }]
Я тоже не понял, зачем нужен правый list

2024-10-02 19:39 UTC, therain7 requested changes

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  (** Function types such as [func()], [func(string) (bool, int)] *)
В чем здесь отличие пустого списка от `None` ?

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Expr_array of type' * expr list option (** Arrays such as [[3]int{3, get_four()}] *)
Тот же вопрос, что выше

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  ; return_types : (ident option * type' option) list option
`[(None, None)]` это что будет?

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_assign of ident list * expr list
Что если количество элементов в списках не равно?

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_decr of ident (** A decrement of a variable: [a--] *)
Похоже, что в Go можно `some_func()++`

2024-10-02 19:39 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  ; init : expr list option (** variables initializers, optional *)
Что если количество элементов в списках разное?

2024-10-02 19:41 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  ; init : expr list option (** variables initializers, optional *)
Сделать список из пар?

2024-10-02 19:42 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
Stmt_block достаточно спорная штука. Т.к. чем отличается `None` у вас в `stmt option` от `Stmt_block` c пустым списком?

2024-10-02 19:43 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  (** Function types such as [func()], [func(string) (bool, int)] *)
Получается везде, где есть список, можно убирать option, и воспринимать пустой список как ```None```?

2024-10-02 19:49 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  ; return_types : (ident option * type' option) list option
Можно ли как-то иначе представить следующие конструкции:
```go
func() (int, string) {...}
func() (a, b, c int) {...}
func() (a bool, b bool) {...}
```
Сверху нет имен, но есть типы, по середине есть имена, но не у всех есть тип, снизу есть всё

2024-10-02 19:50 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  | Stmt_assign of ident list * expr list
Засунуть всё в один список?

2024-10-02 19:52 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  | Stmt_assign of ident list * expr list
```suggestion
  | Stmt_assign of (ident * expr) list
```

2024-10-02 19:54 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  (** Function types such as [func()], [func(string) (bool, int)] *)
Так не будет неоднозначности

2024-10-02 19:55 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  ; return_types : (ident option * type' option) list option
Вы можете вынести возможные варианты в конструкторы ADT

2024-10-02 19:56 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_assign of ident list * expr list
Да

2024-10-02 19:57 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_decr of ident (** A decrement of a variable: [a--] *)
Кажется можно, если возвращать поинтер из функции. Если уверены, что нельзя, то забейте

2024-10-02 19:58 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  ; init : expr list option (** variables initializers, optional *)
Видимо

2024-10-02 20:05 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
В AST должно быть представимо как можно меньше невалидного. 
Для списков можно поддерживать инвариант наличия элементов, вытаскивая первый элемент в аргумент конструктора. 
Или в целом для списков не страшно забить и написать инвариант в комментах. В каком-то роде так будет проще потом.

2024-10-02 20:07 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
Я правильно понимаю, что stmt_block из одного элемента это не то же самое, что этот же элемент вместо block?
Видимо из-за разного scope

2024-10-02 20:12 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  | Stmt_decr of ident (** A decrement of a variable: [a--] *)
Нам не надо делать поинтеры

2024-10-02 20:14 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
Stmt_block подразумевался как тело функции, ифа или фора

2024-10-02 20:27 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
в go нельзя делать делать произвольные блоки через {}?
может вам не нужен этот конструктор вообще

2024-10-02 20:28 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_decr of ident (** A decrement of a variable: [a--] *)
ок

2024-10-02 20:33 UTC, shakareem commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
Можно, узнал только что. Значит всё-таки нужен, как раз для скоупа

2024-10-02 20:57 UTC, Kakadu commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
@therain7 Предлагаю всё это отложить на тестирование quickcheckом.

2024-10-02 21:22 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Stmt_block of stmt list (** Block of statements in curly braces *)
Кажется, что тут немало проблем легко заметить просто глазами.
Предлагаю им исправить все, что я сейчас заметил так, а остальное (если оно есть) уже можно отложить

2024-10-03 10:26 UTC, therain7 requested changes
Сделайте так, чтобы зануда не ругалась. И будет +

2024-10-03 10:26 UTC, therain7 commented on Go/lib/ast/ast.ml
> +[@@deriving show { with_path = false }]
`No_return_values` можно закинуть выше как `option`.
`Ident_one_type` можно не делать, а явно приписывать одинаковые типы всем идентификаторам в `Ident_all_types` в парсере. Потом будет чуть проще

2024-10-03 10:26 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  { args : (ident list * type') list
Можно выкинуть `list` из `ident list`

2024-10-03 10:26 UTC, therain7 commented on Go/lib/ast/ast.ml
> +    and expr in all pair either Some or None *)
Последний инвариант при желании можно поддержать программно, если явно вынести разделить случай, когда всех выражений нет, либо все есть. Примерно так же, как с `return_values`

2024-10-03 13:18 UTC, therain7 approved these changes
нрав

2024-10-03 13:18 UTC, merged