Add AST of Haskell (Nikita Shchutskii, Kostya Oreshin)
Kakadu/fp2024 pull request #13
Opened 2024-09-30 18:22 UTC by TerrMen

- AST of Haskell language in [/lib/ast.mli](https://github.com/TerrMen/Haskell/blob/ast/Haskell/lib/ast.mli)
- Example of factorial represented in AST [/bin/main.ml](https://github.com/TerrMen/Haskell/blob/ast/Haskell/bin/main.ml)

2024-10-01 10:48 UTC, Kakadu requested changes
Неплохая попытка, что почему AST --- это факториал, я не понял.

2024-10-02 14:53 UTC, Szczucki commented on Haskell/lib/ast.ml
> +  | PNul (* $*)
Как мы поняли, синтаксис конструкций, отвечающих за представление деревьев, определяем мы сами. Для обозначения нод мы выбрали конструкцию вида (<data>; <left son>; <right son>), так как не нашли типов/конструкций, которые в Хаскель представляются круглыми скобками, между которыми содержатся разделенные точкой с запятой элементы. Для обозначения пустого дерева (в т.ч осутствующего сына у вершины) мы выбрали знак '$'.  
Нам стоило следовать какому-то уже существующему синтаксису в этом вопросе? Или проблема в том что выбранные обозначения конфликтуют с уже существующими в Хаскель? Нам известно  только об операторе применения функции (Function application operator)

2024-10-02 17:06 UTC, Kakadu commented on Haskell/lib/ast.ml
> +  | PNul (* $*)
Вы выбрали списки и maybe как в х-е. Я не ожидал, что кто-то будет выдумывать синтаксис для деревьев.

2024-10-02 22:15 UTC, Szczucki commented
Попытались устранить недостатки отмеченные в ревью. В процессе внесения изменений заметили, что в наших конструкторах для паттернов представимо много всякой ерунды. Самые вопиющие случаи исключили, но все еще представимо предостачно некорректных паттернов вроде [ (x, y, z), (u, v) ] или [1, True, (x, y)].  Как мы поняли, отлавливать такое можно и нужно ещё в парсере. Что нам с этим всем делать: так все и оставить (возможно прописав в документации к типу какие-то правила, определяющие корректность ?) или стоит как-то дальше пытаться доработать ast?

2024-10-03 14:26 UTC, Kakadu commented
> все еще представимо предостачно некорректных паттернов вроде [ (x, y, z), (u, v) ] или [1, True, (x, y)]. Как мы поняли, отлавливать такое можно и нужно ещё в парсере.

В тапчекере

2024-10-03 14:27 UTC, Kakadu commented on Haskell/lib/ast.ml
> +type const =
Fix this

2024-10-03 14:27 UTC, Kakadu commented on Haskell/lib/ast.ml
> +type comprehension =
fix this

2024-10-03 14:31 UTC, Kakadu requested changes
Тут есть ещё к чему придраться. Предлагаю исправить линтер про лицензию и взаимную рекурсию, а остальное доделать в следующих PR

2024-10-04 21:03 UTC, merged