Add a factorial parser of interpreter "OCaml + printf" by Rodionov Maxim and Zaikin Vladimir
Kakadu/fp2024 pull request #32
Opened 2024-10-13 17:39 UTC by Friend-zva

Добавлено:
 • минимальная реализация для парсинга факториала;
 • тесты реализованных парсеров.

2024-10-14 15:10 UTC, therain7 requested changes
*Местами как-то очень похоже на мой парсер, который писал год назад :)*
*Смотрели туда в том числе или совпадение..?*

В целом очень неплохо. Исправьте замечания **до 21 октября**, будет +

2024-10-14 15:10 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +let parse str = parse_string ~consume:All parse_structure str
```suggestion
let parse = parse_string ~consume:All parse_structure
```

2024-10-14 15:10 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +       parse_value_binding_list
Рекомендую посмотреть на `let*`, может так больше понравится

2024-10-14 15:10 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +        (return (fun exp1 exp2 -> Exp_apply (exp1, [ exp2 ])))
Наверное хотелось бы парсить `f x y` как один `Exp_apply`

2024-10-16 14:13 UTC, RodionovMaxim05 commented on OCamlPrintf/lib/parser.ml
> +       parse_value_binding_list
Точно заменим в 'parse_ident', 'parse_pat_tuple' и 'parse_exp_tuple', так как с let* будет намного более читаемо. Что касается других мест, то в документации библиотеки [angstrom](https://ocaml.org/p/angstrom/0.14.1/doc/Angstrom/index.html#val-lift4), если я правильно понимаю, рекомендуется использовать lift, т.к. они более эффективны и, вроде, в остальных местах читаемость неплохая. Или же все-таки стоит заменить везде на let* ?
![Screenshot_20241016_171056](https://github.com/user-attachments/assets/d1ccfdda-14b4-4778-87be-61913c2a552b)

2024-10-16 15:00 UTC, Friend-zva commented on OCamlPrintf/lib/parser.ml
> +    let parse_cur_pat =
Это `current`, но предполагаю, что вопрос не в этом.

2024-10-16 15:36 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    let parse_cur_pat =
что значит current в этом контексте я не пон, но лан

2024-10-16 15:37 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +       parse_value_binding_list
Там написано, что они эффективинее, чем набор `<*>`

2024-10-19 14:30 UTC, therain7 approved these changes
неплохо

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  then fail (String.concat [ "Impossible name: "; "\""; ident; "\""; "." ])
может sprintf какой-нибудь

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    | _ -> false)
Char.is_digit

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  in
fold?

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  >>| fun exp_list -> if is_empty exp_list then var else Exp_apply (var, exp_list)
`exp_list = []` .
впрочем тут не должно быть many1?

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    parse_exp_tuple parse_exp <|> parse_exp)
порядок приоритета?

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +        ; parse_exp_ifthenelse parse_full_exp
`parse_exp_construct` разве не здесь будет в вашем случае?

2024-10-19 14:30 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    parse_exp_tuple parse_exp <|> parse_exp)
и у вас не парситcя [1,2]

2024-10-19 14:31 UTC, merged

2024-10-26 17:46 UTC, Friend-zva commented on OCamlPrintf/lib/parser.ml
> +        ; parse_exp_ifthenelse parse_full_exp
Хотелось бы, но в таком случае `parse_exp_sequence` забирает инициативу...

2024-10-26 17:49 UTC, Friend-zva commented on OCamlPrintf/lib/parser.ml
> +  >>| fun exp_list -> if is_empty exp_list then var else Exp_apply (var, exp_list)
> `exp_list = []`.

Вроде zanuda ругалась на это. 

> впрочем тут разве не должно быть many1?

Можно конечно переделать, но нам показалось так удобнее. (если просто заменить на many1 не работает)

2024-10-26 17:51 UTC, Friend-zva commented on OCamlPrintf/lib/parser.ml
> +    parse_exp_tuple parse_exp <|> parse_exp)
> порядок приоритета?

Где могли порядок учли (в `choice`), а все, что не в нем, было вынесено, потому что только так работает. (надеюсь, что исправим)

2024-10-27 12:49 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +        ; parse_exp_ifthenelse parse_full_exp
пон

2024-10-27 12:49 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    parse_exp_tuple parse_exp <|> parse_exp)
только так работает

2024-10-27 12:50 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  >>| fun exp_list -> if is_empty exp_list then var else Exp_apply (var, exp_list)
справедливо