Add a factorial parser of miniML "OCaml + Polymorphic variants types" by Suponev Ilia
Kakadu/fp2024 pull request #33
Opened 2024-10-13 21:53 UTC by IliaSuponeff

Added a parser for basic structures of miniML `"OCaml + Polymorphic variants types"`. 

Added elements:
* parser of structures:
  - literals
  - patterns
  - expressions
  - struct_item
* tests of all program elements

2024-10-15 09:41 UTC, therain7 requested changes
сложно

*исправления **до 22 октября***

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.mli
> +type 'a parser = parser_state -> 'a parse_result [@@deriving show { with_path = false }]
Можно было попрятать все особенности реализации за абстрактным типом, например как это сделано в angstrom

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/printer.ml
> +let string_of_program_parse_result = string_of_parse_result show_program
Зачем весь этот boilerplate? Верхней функции достаточно. Пользуйтесь параметрическим полиморфизмом, раз пишете на окамле

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  if is_digit (List.nth l 0)
`List.hd`, но энивей выглядит так себе.
Сделайте лучше два парсера один под первой символ, второй под остальные.
Так будет более явно, что нельзя писать первым. Тем более вы упустили идентификаторы вида `a'b`

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    [!] This parser returns also [ParseSuccess] or [ParseFail] *)
К чему эти комментарии?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  >>= fun cl -> preturn (BoolLiteral (List.length cl = 4))
Давайте не так

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +let rec pattern_parser state = (skip_ws *> (pvariable <|> ptuple)) state
```suggestion
let rec pattern_parser = (skip_ws *> (pvariable <|> ptuple))
```

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +and pvariable state = (skip_ws *> (ident >>= fun id -> preturn (PVar id))) state
Сделайте себе fmap (>>|)

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.ml
> +;;
чем это отличается от *>?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +let const_expr = skip_ws *> integer <|> boolean >>= fun id -> preturn (Const id)
id?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    - expression block: [(<expr>; ...; <expr>)]
а если скобок нет, то нельзя ;?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    ; { oper_view = "<"; oper_ast = Lt }
в порядке приоритета?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +
Давайте вы все, что выше перепишите аккуратнее и возможно на let*, т.к. это не читаемо

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
что вы тестируете тут?

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/bin/main.ml
Перепишите в соотвествии с требованиями

2024-10-15 09:41 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/parser_tests.ml
> +  Format.printf "%s" (string_of_literal_parse_result (parse integer "123"));
тяжело читать

2024-10-15 13:29 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    ; { oper_view = "<"; oper_ast = Lt }
Как я понял операторы сравнения имеют равный приоритет в OCaml, поэтому не имеет большой разницы в каком порядке их парсить.

2024-10-15 16:12 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.mli
> +type 'a parser = parser_state -> 'a parse_result [@@deriving show { with_path = false }]
Я исходил из примеров в презентации

2024-10-15 16:21 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
Здесь приведён тест из предыдущего PR, представление AST для факториала

2024-10-15 20:24 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
Так а в чем тест заключается?

2024-10-15 20:26 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.mli
> +type 'a parser = parser_state -> 'a parse_result [@@deriving show { with_path = false }]
Тем не менее "Можно было попрятать все особенности реализации за абстрактным типом, например как это сделано в angstrom"

2024-10-15 20:44 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
В том что он, факториал, представим в AST

2024-10-15 21:09 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
Если вы его спарсить можете, то он представим

2024-10-15 21:22 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/tests/ast_tests.ml
Понял

2024-10-16 07:34 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    [!] This parser returns also [ParseSuccess] or [ParseFail] *)
Если вы про `[!] This parser returns also [ParseSuccess] or [ParseFail] ` эту строчку, то это больше пометка, что данный парсер никогда не вернёт ошибку как результат.

2024-10-16 07:35 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  >>= fun cl -> preturn (BoolLiteral (List.length cl = 4))
Если переписать на 
```ocaml
let boolean =
  skip_ws *> (keyword "true" >>| fun _ -> BoolLiteral true)
  <|> (keyword "false" >>| fun _ -> BoolLiteral false)
;;
```

2024-10-16 07:38 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +let rec pattern_parser state = (skip_ws *> (pvariable <|> ptuple)) state
Это не возможно в связи с ошибкой:
```text
File "lib/parser.ml", line 88, characters 25-58:
88 | let rec pattern_parser = skip_ws *> (pvariable <|> ptuple)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This kind of expression is not allowed as right-hand side of `let rec'
```

2024-10-16 10:45 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  >>= fun cl -> preturn (BoolLiteral (List.length cl = 4))
так лучше

2024-10-16 10:47 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +    [!] This parser returns also [ParseSuccess] or [ParseFail] *)
Это важно? Если это очень важно, то в камле есть возможности, чтобы закодировать это через систему типов.
Комментарии быстро устаревают, а инварианты, указанные в них, никак не энфорсятся компилятором.

Это скорее придирка. Можете не менять ничего

2024-10-16 12:22 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +let rec pattern_parser state = (skip_ws *> (pvariable <|> ptuple)) state
Зачем `rec` здесь

2024-10-18 10:48 UTC, therain7 approved these changes
norm

2024-10-18 10:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/bin/REPL.ml
> +       (parse program_parser input))
Немного криж

2024-10-18 10:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/interpret_tests.t
> +
Для читаемости тестов лучше подавать небольшой вход прям здесь в stdin

2024-10-18 10:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/tests/parser_tests.ml
Предполагалось, что вы будете тестировать парсер cram тестами на REPL

2024-10-18 10:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.ml
> +
Кажется, вы fold переизобретаете и при этом не tail рекурсивно

2024-10-18 10:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  }
Не очень понятно, к чему это в начале файла

2024-10-18 10:48 UTC, merged

2024-10-18 14:23 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  }
В начале идут некоторые вспомогательные функции и типы, которые потребуются только здесь

2024-10-18 14:30 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.ml
> +
Нет, это `<|>` для парсеров

2024-10-18 14:35 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser.ml
> +  }
можно их поближе к месту использования

2024-10-18 14:36 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/parser_utility.ml
> +
И?