Add Haskell parser of factorial (Nikita Shchutskii, Kostya Oreshin)
Kakadu/fp2024 pull request #34
Opened 2024-10-13 22:12 UTC by sevenbunu

- parser in [/lib/parser.ml](https://github.com/sevenbunu/Haskell/blob/parser/Haskell/lib/parser.ml)
- example of usage in [/bin/main.ml](https://github.com/sevenbunu/Haskell/blob/parser/Haskell/bin/main.ml)

2024-10-14 12:20 UTC, Kakadu requested changes
Я там немножко попридирался, но не запускал. Надеюсь, что работает.

2024-10-14 12:20 UTC, Kakadu commented on Haskell/lib/ast.ml
> +type pattern = ident list * pat * tp option [@@deriving show { with_path = false }]
список? Что за список?

2024-10-14 12:20 UTC, Kakadu commented on Haskell/lib/parser.ml
> +    ; "rec"
А такое есть в хаскеле? Вы планируете сделать https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/arrows.html ?!)

2024-10-14 12:20 UTC, Kakadu commented on Haskell/lib/parser.ml
> +  <|> (let* x = satisfy (fun c -> Char.equal '_' c) in
eta?

2024-10-14 12:20 UTC, Kakadu commented on Haskell/lib/parser.ml
> +let b e b =
Думаю, имено можно было выбрать по-удачнее...

2024-10-14 12:20 UTC, Kakadu commented on Haskell/lib/parser.ml
> +  and+ el_br = string "else" **> e in
Если мы напишем `ifa thenb elsec` не распарсит ли он это, не смотря на то, что не должен? Вроде надо проверять, что после ключевого слова не продолжается идентификатор.

2024-10-14 12:20 UTC, Kakadu commented on Haskell/tests/parser_test.t
> +  (FunBind (((Ident "fac"), None), ([], (PIdentificator (Ident "n")), None),
Возможно, стоит почитать про HEREDOC

2024-10-14 12:20 UTC, Kakadu commented
Ну и сделать хорошо линтеру придется.

2024-10-18 20:04 UTC, Szczucki commented
Нынешний парсер для Maybe подходит для инпута с факториалом, но в общем случае не сможет работать, так как в Хаскеле конструкторы (в т.ч. и Just) - полноценные функции (то есть валидны конструкции вроде f = Just или y = map Just [1, 2, 3]). Есть идея парсить Just, как анономную функцию вида Lambda ([ ], PIdentificator (Ident "x"), None), [], OptionBld (Identificator x)). Это адекватное решение?

2024-10-18 21:57 UTC, Kakadu commented on Haskell/tests/parser_test.t
> +  (FunBind (((Ident "fac"), None), ([], (PIdentificator (Ident "n")), None),
?

2024-10-18 22:12 UTC, Kakadu commented
> Нынешний парсер для Maybe подходит для инпута с факториалом, но в общем случае не сможет работать, так как в Хаскеле конструкторы (в т.ч. и Just) - полноценные функции (то есть валидны конструкции вроде f = Just или y = map Just [1, 2, 3]). Есть идея парсить Just, как анонимную функцию вида Lambda ([ ], PIdentificator (Ident "x"), None), [], OptionBld (Identificator x)). Это адекватное решение?

Ещё можно отсавить в дереве просто Just без аргументов. И потом уже разруливать арность.

2024-10-18 22:13 UTC, Kakadu approved these changes
Я попридирался, но вроде с факториалом справились.
Пофиксите мелочи и я помержу.

2024-10-18 22:13 UTC, Kakadu commented on Haskell/lib/ast.ml
>    | Plus (** + *)
https://kakadu.github.io/fp2024/docs/Haskell/Haskell_lib/Ast/index.html
Если открыть доку, там какой-то квадратик.

2024-10-18 22:13 UTC, Kakadu commented on Haskell/lib/parser.ml
> +;;
У вас до этого все имена функций были существительные, а тут вдруг --- глагол...

2024-10-18 22:13 UTC, Kakadu commented on Haskell/tests/parser_test.t
>                   ((Const (Int 0)), None))),
А в дереве не должен быть где-то идентификатор "otherwise"? Что-то не вижу.

2024-10-19 13:48 UTC, Szczucki commented on Haskell/tests/parser_test.t
>                   ((Const (Int 0)), None))),
Мы представляли otherwise в ast как тождественное True. Сейчас ошибочность такого подхода осознана и парсер исправлен.

2024-10-19 15:53 UTC, Szczucki commented on Haskell/lib/parser.ml
> +;;
Название функции изменено в том же коммите; или замечание относится и к конструктору тоже?

2024-10-19 16:20 UTC, merged