Added factorial parser: OCaml + Recursive values (Viacheslav Sidorov and Danila Rudnev-Stepanyan)
Kakadu/fp2024 pull request #36
Opened 2024-10-14 19:32 UTC by xamelllion

Добавлено:
• минимальная реализация для парсинга факториала
• некоторые тесты реализованных парсеров

2024-10-15 11:46 UTC, therain7 requested changes
Исправьте замечания и сделайте REPL (в том смысле, что было в требованиях) **до 15 октября**.

И у вас что-то не то с парсингом операторов. Посмотрите на результат парсинга `2 + (2 + 2)`

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +(* Number of parser *)
пон

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  let* sign = choice [ token "-"; token "+"; token "" ] in
Наверное лучше option, чем token "", но сойдет.
Впрочем у вас все равно конфликты с унарными операциями скорее всего здесь

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    ; token "nil" *> return (ExprLiteral NilLiteral)
Где в камле такой литерал искать?

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  let* p = take_while1 is_letter in
нет

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  let* rest = take_while (fun c -> is_letter c || is_digit c || Char.equal c '_') in
`a'b`

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +let pvariable =
Как вы различаете переменные и идентификаторы?

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  | _ as name -> return (ExprVariable name)
```suggestion
  | name -> return (ExprVariable name)
```

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +let parse_rec_flag = ws *> option NonRec (token "rec" *> return Rec)
`let reca=1`

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    *>
можно положить это в верхний или нижний парсер, чтобы форматирование было аккуратнее

2024-10-15 11:46 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +;;
наверное это нужно только в тестах. стоит положить поближе к ним

2024-10-15 12:31 UTC, Kakadu commented
> И у вас что-то не то с парсингом операторов. Посмотрите на результат парсинга `2 + (2 + 2)`
> 

Как можно `2 + (2 + 2)` распарсить непрпвильно?!

2024-10-15 13:05 UTC, therain7 commented
```
[(SEval
    (ExprApply ((ExprLiteral (IntLiteral 2)),
       (ExprUnOperation (UnaryPlus, (ExprLiteral (IntLiteral 2)))))))
   ]
```
впрочем с 2 + 2 тоже что-то не то

2024-10-19 18:45 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +    ; token "nil" *> return (ExprLiteral NilLiteral)
Услышали

2024-10-19 18:45 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +  let* p = take_while1 is_letter in
Поправил

2024-10-19 18:52 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +let pvariable =
Переменная не может являться ключевым словом, идентификатор может

2024-10-19 18:52 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +let parse_rec_flag = ws *> option NonRec (token "rec" *> return Rec)
Исправленно

2024-10-19 18:53 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +;;
То что используется в тестах - перенес в тесты, оставил одну функцию, которая используется в bin/main.ml

2024-10-19 19:00 UTC, xamelllion commented
> > И у вас что-то не то с парсингом операторов. Посмотрите на результат парсинга `2 + (2 + 2)`
> 
> Как можно `2 + (2 + 2)` распарсить непрпвильно?!

Исправлено

2024-10-19 19:02 UTC, xamelllion commented
Медитация над рекурсивным спуском прошла успешно

2024-10-19 19:09 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +  let* sign = choice [ token "-"; token "+"; token "" ] in
Для парсинга факториала подходит, в следующей задаче сделаем красиво

2024-10-19 19:17 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> +  let* rest = take_while (fun c -> is_letter c || is_digit c || Char.equal c '_') in
Поправил

2024-10-22 19:36 UTC, therain7 approved these changes
ok

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/ast.ml
> +  | SValue of rec_flag * binding
все-таки по требованиям у вас здесь будет list

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    | _ -> true)
take_till?

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  | "_" -> fail "Wildcard can't be used as indetifier"
видимо эта ветка unreachable, если парсер не кривой

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +;;
string "rec" ??

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +      (option None (token "else" *> (peif <|> pe) >>| Option.some)))
здесь вы уже слышали про option

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    choice [ pelet expr; pefun expr; ife ])
1 + if a then b else c

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +let parse s = parse_string ~consume:Prefix structure s
у вас с `Prefix` некорректные программы могут парситься.

2024-10-22 19:36 UTC, therain7 commented on OCamlRV/tests/parser.ml
> +
корректность не важна?

2024-10-22 19:36 UTC, merged

2024-10-22 19:53 UTC, Dabzelos commented on OCamlRV/tests/parser.ml
> +
думаю важна, но в целом мы проверяем много случаев на
А) вообще возможность распарсить,
б) ниже есть некоторое множество expect_test, которые проверяют корректность

а вообще в какой то версии коммитов вроде все эти тесты были не parse to bool, а по настоящему AST возвращали, со Славой поищем

2024-10-22 19:56 UTC, therain7 commented on OCamlRV/tests/parser.ml
> +
можно сказать, что эти тесты совсем не показательны

2024-10-22 19:57 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +let pvariable =
подумайте, где в программе могут быть идентификаторы, которые могут быть ключевым словом

2024-10-22 22:01 UTC, Dabzelos commented on OCamlRV/tests/parser.ml
> +
Вполне да, но опять же они на первой версии парсера написанной мной выдавали AST, потом после того как слава внес большие изменения после первого дедлайна пришлось их превратить в некоторый атавизм,
Я думаю мы исправим это

2024-11-01 13:12 UTC, xamelllion commented on OCamlRV/lib/ast.ml
> +  | SValue of rec_flag * binding
Done