Add QChecker, Shrinker, Pretty Printer for OCaml bidirectional records. Sophia Kozyreva, Maksim Shipilov
Kakadu/fp2024 pull request #42
Opened 2024-11-11 18:40 UTC by mshipilov5

QChecker and Shrinker could be found at lib/qcheck.ml
Pretty Printer is located at lib/pr_printer.ml

Run Qchecker with `dune exec lib/run_qcheck.exe`

2024-11-12 15:10 UTC, Kakadu commented on OcamlBR/lib/parser.ml
> +;;
Может всё-таки fix?

2024-11-12 15:10 UTC, Kakadu commented on OcamlBR/OcamlBR.opam
> -  "ppx_expect"
Зачем?

2024-11-12 15:12 UTC, Kakadu commented on OcamlBR/lib/pr_printer.ml
> +;;
:((

2024-11-12 15:16 UTC, Kakadu commented on OcamlBR/lib/ast.ml
>  (* anonymous functions, e.g. fun x y -> x + 1 - y, arguments num >= 1  *)
:(

2024-11-12 15:16 UTC, Kakadu reviewed
Товарищ Сухарев наверняка сможет выжать ещё сока.

2024-11-14 22:44 UTC, therain7 requested changes
- доделайте парсер до условия miniml
- сделайте принтер по-настоящему pretty с точки зрения расставления скобок (учитывайте приоритет и ассоциативность операторов)
- запустите квикчек сами все-таки

дедлайн на все все **20 ноября**

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/ast.ml
> +  | SValue of rec_flag * id * expr * expr
pattern
и взаимно рекурсивные определения

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/dune
> +(executable
в директории lib. лан

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +  | "None" -> true
это не то, что бы киворды, но ок сойдет

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
>       | "" ->
как-то стремно это. я не очень пон, зачем вы условие проотрицали

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +let ppattern = choice [ pat_const; pat_var; pat_any ]
скудно

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
>         (pparens varname <|> varname)
pattern

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +  (* let pexpr = psqparens pexpr in *)
?

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +  psqparens (sep_by semicols pexpr <* (semicols <|> pwhitespace) >>| fun x -> Elist x)
`semicols <|> pwhitespace`
а если semicols И whitespace?

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
>      let ite_expr = pbranch (expr <|> atom_expr) <|> atom_expr in
поясните к чему choice внутри скобок

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +    | Elet (r, id, e1, e2) -> SValue (r, id, e1, e2)
откуда e2 в SValue?
вы умеете просто `let a = 1`?

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +let parse_expr str = parse_string ~consume:All structure str
eta?

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/pr_printer.ml
> +let pp_const = function
функции, которые называются pp_*, обычно возвращают не строки.
даже у вас

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/pr_printer.ml
> +  | Eif_then_else (e1, e2, None) -> "if " ^ pp_expr e1 ^ " then " ^ pp_expr e2
printf..

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/pr_printer_tests.ml
> +    Stdlib.print_endline (show_structure structure)
прикольно

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/qcheck.ml
здесь замечание про deriving, который вы можете прочитать в любом другом PR, отсмотренном мной

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/run_qcheck.ml
> +  let _ = run_manual () in
это бы на dune runtest запускать

2024-11-14 22:44 UTC, therain7 commented on OcamlBR/lib/ast.ml
>  (* anonymous functions, e.g. fun x y -> x + 1 - y, arguments num >= 1  *)
давайте я скажу, что плохие программы не должны быть представимы в типах

2024-11-15 09:32 UTC, mshipilov5 commented on OcamlBR/lib/pr_printer_tests.ml
> +    Stdlib.print_endline (show_structure structure)
Не до конца ясно, нам оставить такое конструирование строки или переделать на printf для каждого элемента ast?

2024-11-15 10:22 UTC, therain7 commented on OcamlBR/lib/pr_printer_tests.ml
> +    Stdlib.print_endline (show_structure structure)
"переделать на printf для каждого элемента ast" ?

2024-11-15 10:29 UTC, mshipilov5 commented on OcamlBR/lib/pr_printer_tests.ml
> +    Stdlib.print_endline (show_structure structure)
код соседней команды для примера:
```
let rec pp_expr =
   let rec helper ppf = function
     | ExprVariable v -> fprintf ppf "%s" v
     | ExprLiteral l -> fprintf ppf "%a" pp_literal l
     | ExprBinOperation (op, e1, e2) ->
       fprintf ppf "(%a %a %a)" helper e1 pp_binop op helper e2
```

Мой принтер формирует одну большую строку, а в коде выше выводится всё поэтапно. Насколько это важно в контексте принтера и нужно ли нам заменить конструирование строки на поэтапный вывод?

2024-11-15 10:30 UTC, mshipilov5 commented on OcamlBR/lib/pr_printer.ml
> +  | Eif_then_else (e1, e2, None) -> "if " ^ pp_expr e1 ^ " then " ^ pp_expr e2
в т.ч. актуально к этому комментарию

2024-11-15 10:33 UTC, mshipilov5 commented on OcamlBR/lib/pr_printer.ml
> +  | Eif_then_else (e1, e2, None) -> "if " ^ pp_expr e1 ^ " then " ^ pp_expr e2
Пришла ясность по поводу формирования строки, но теперь не понятно о чём комментарий "printf" и требует ли это каких-то изменений?

2024-11-15 11:41 UTC, therain7 commented on OcamlBR/lib/pr_printer.ml
> +  | Eif_then_else (e1, e2, None) -> "if " ^ pp_expr e1 ^ " then " ^ pp_expr e2
вы в си строки тоже так конкатенируете?

2024-11-22 23:32 UTC, Kakadu requested changes

2024-11-24 11:05 UTC, Kakadu commented
```
✗ dune exec lib/run_qcheck.exe -- -seed 133064311 -gen 10
random seed: 133064311        

--- Failure --------------------------------------------------------------------

Test anon_test_1 failed (3 shrink steps):

let  _cBIh = in ;;
================================================================================
failure (1 tests failed, 0 tests errored, ran 1 tests)
```

2024-11-25 12:20 UTC, therain7 requested changes
- `доделайте парсер до условия miniml`. **приписывание костыльные, при этом без списков, туплов и функциональных типов**
- `сделайте принтер по-настоящему pretty с точки зрения расставления скобок (учитывайте приоритет и ассоциативность операторов)`. **не сделали**

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/bin/astEx.ml
что это

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/ast.ml
> +type id = Id of string * string option [@@deriving show { with_path = false }]
?

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +    choice [ pstoken "int"; pstoken "string"; pstoken "bool" ] >>| fun t -> Some t
списки еще

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/ast.ml
> +type id = Id of string * string option [@@deriving show { with_path = false }]
я понял, подразумевается тип. это костыль.
посмотрите, как в окамле это

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +;;
?

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/parser.ml
>      let ite_expr = pbranch (expr <|> atom_expr) <|> atom_expr in
не пояснили

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +  psqparens (sep_by semicols pexpr <* (semicols <|> pwhitespace) >>| fun x -> Elist x)
проигнорили

2024-11-25 12:20 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +    choice [ pstoken "int"; pstoken "string"; pstoken "bool" ] >>| fun t -> Some t
и функции

2024-11-25 12:20 UTC, merged