Add a QChecker ("OCaml + printf" by Rodionov Maxim and Zaikin Vladimir)
Kakadu/fp2024 pull request #43
Opened 2024-11-11 19:19 UTC by RodionovMaxim05

Добавлено:
- Pretty Printer;
- QChecker.

Дополнительно:
- Исправлены недочеты парсера.

Запустить Qchecker можно с помощью `dune exec ./_build/default/lib/run_qchecker.exe`

2024-11-13 22:23 UTC, therain7 requested changes
доделайте парсер, принтер и квикчек и все остальное до полноценного miniml из тз

**к 21 октября** все все должно быть сделано

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/dune
> +(executable
в директории `lib`

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  return (Exp_tuple (List.cons first_exp rest_exps))
::?

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +    let parse_exp = parse_exp_sequence parse_exp in
у sequence приоритет меньше, чем у открытой части if. но можете забить

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +let pp_ident ppf id = fprintf ppf "%s" id
%s нужен?

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +        " and "
pp_print_list?

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +      | [] -> fprintf ppf "%s" expression
это некорректный случай

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +          | _ -> false
непон, почему именно + и -

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/tests/test_parser.ml
> +        (Exp_sequence (
у вас же *pretty* принтер есть

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/tests/test_pprinter.ml
> +  [%expect "let f = fun x y z -> if x = 0 && y = 1 || z >= 2 then 2 else 26;;"]
правда лишние скобки не ставятся? прям везде везде?
учитывая и приоритет, и ассоциативность

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/qchecker.ml
идея была в том, что вы будете использовать `deriving qcheck`, а не писать свои генераторы, которые можно специально случайно написать так, что они не будут генерить ничего плохого.

кстати пустые списки там, где их не должно быть, по-хорошему не должны быть представимы в аст

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/qchecker.ml
> +  let gen_ident = string_size (int_range 1 3) ~gen:gen_char
операторы

2024-11-13 22:23 UTC, therain7 commented on OCamlPrintf/lib/qchecker.ml
> +                   (list_size (int_range 2 5) (self (n / coefficient))) )
больше 5 **точно** не нужно?

2024-11-14 15:42 UTC, Friend-zva commented on OCamlPrintf/tests/test_parser.ml
> +        (Exp_sequence (
Убрать тесты для `parser` и `pretty printer` и оставить только на композицию? Это же будет не unit-тестирование, к тому же printer, по идеи, на том же этапе разработке что и parser.

2024-11-14 17:04 UTC, therain7 commented on OCamlPrintf/tests/test_parser.ml
> +        (Exp_sequence (
было бы приятнее видеть результат тестов на парсер красиво напечатанным.
понятно, что если одна и та же ошибка и в парсере, и в принтере, то можно не заметить ее на тестировании.
но смотрите сами, что меньшее зло

2024-11-14 21:27 UTC, Kakadu commented on OCamlPrintf/tests/test_parser.ml
> +        (Exp_sequence (
>  Это же будет не unit-тестирование,
я никогда не имел в виду, что вы должны делать Unit-тестирование.

2024-11-15 17:49 UTC, Friend-zva commented on OCamlPrintf/lib/qchecker.ml
> `deriving qcheck`

Несмотря на то, что в [readme](https://github.com/c-cube/qcheck/tree/main/src/ppx_deriving_qcheck#mutual-recursive-types) явно демонстрируется возможность использования `deriving qcheck` для взаимно рекурсивных типов, у нас не получается это сделать. 

```shell
File "lib/ast.ml", lines 31-63, characters 0-47:
31 | type value_binding =
32 |   { pat : pattern
33 |   ; exp : expression
34 |   }
35 |
...
60 |   | Exp_ifthenelse of expression * expression * expression option
61 |   (** [if E1 then E2 else E3] *)
62 |   | Exp_sequence of expression * expression (** [E1; E2] *)
63 | [@@deriving show { with_path = false }, qcheck]
Error: Unbound value n
```

Мы чуть изменили пример из readme выше и получили такую же ошибку именно с `record`. Лично мне кажется, что почему-то это (`record` с взаимно рекурсивными типами) невозможно сделать (даже с `[@gen ...]`), но я буду очень рад ошибаться.
<img width="386" alt="image" src="https://github.com/user-attachments/assets/57e26c9f-1353-4eb4-92f0-707094e92d4f">

2024-11-15 22:28 UTC, Kakadu commented on OCamlPrintf/lib/qchecker.ml
У меня рабоет.

2024-11-16 11:39 UTC, therain7 commented on OCamlPrintf/lib/qchecker.ml
У меня тоже не работало.

2024-11-16 11:39 UTC, therain7 commented on OCamlPrintf/lib/qchecker.ml
Придумайте что-нибудь, чтобы работало

2024-11-16 17:28 UTC, Kakadu commented on OCamlPrintf/lib/qchecker.ml
А какой там код генерится?

2024-11-21 19:37 UTC, Kakadu commented on OCamlPrintf/README.md
> +dune exec ./_build/default/tests/run_qchecker.exe # Run manual and auto generators with shrinker.
```suggestion
dune exec /tests/run_qchecker.exe # Run manual and auto generators with shrinker.
```

2024-11-21 19:37 UTC, Kakadu commented on OCamlPrintf/README.md
> +cd OcamlPrinf/
```suggestion
cd OCamlPrinf/
```

2024-11-27 20:20 UTC, therain7 approved these changes
<img width="358" alt="image" src="https://github.com/user-attachments/assets/fefe8a9d-0cac-489f-a7af-d34e7afbcbbb">

как-то вы не до конца справились в pretty в pretty принтере.

в остальном приемлимо

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/parser.ml
> +  then var
var?

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +    in
вы тут вручную приоритет пытаетесь настроить, хотя могли бы загуглить, как это делать в общем случае в принтере. я даже вам ссылку кидал в чат

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +    pp_with_condition_on_arrow second_type;
first_type :: second_type :: type_list ??

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +    if not (Base.List.is_empty value_binding_list)
просто приделайте голову к списку и обрабатывайте все одинаково.
это выглядит очень стремно

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +                    pp_expression
я надеюсь, вы понимаете, что это может и должно выглядеть не так

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +         | _ -> ()
где-то я уже это видел

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/lib/pprinter.ml
> +;;
и это тоже

2024-11-27 20:20 UTC, therain7 commented on OCamlPrintf/tests/run_qchecker.ml
Судя по `dune`, это не бинарь. И не тест.
Вы верите, что оно просто как-нибудь само запустится на runtest?
Так еще и seed не прибит

2024-11-27 20:21 UTC, merged