F# + Active Patterns: Add QCheck, Pretty Printer. Ksenia Kotelnikova, Gleb Nasretdinov.
Kakadu/fp2024 pull request #44
Opened 2024-11-11 20:24 UTC by Ycyken

2024-11-12 11:39 UTC, Kakadu commented on FSharpActivePatterns/lib/parser.ml
> +  >>= (fun name -> return name)
?

2024-11-12 11:40 UTC, Kakadu commented on FSharpActivePatterns/lib/parser.ml
> +  p_ident
может всё-таки let*, а?

2024-11-12 11:41 UTC, Kakadu commented on FSharpActivePatterns/lib/parser.ml
> +;;
Я подозреваю, что он не может отличить "Some1" от "Some 1"...

2024-11-12 11:43 UTC, Kakadu commented on FSharpActivePatterns/lib/prettyPrinter.ml
> +  | Match _ -> fprintf fmt "MATCH WIP"
Ну, вы сами всё понимаете же, да?

2024-11-12 11:45 UTC, Kakadu requested changes
Я думаю, вы сами понимаете, где не доделано.

2024-11-19 20:22 UTC, Kakadu commented
```
$ dune exec lib/tests/run_qcheck.exe -- -seed 144052454 -gen 1
random seed: 144052454              
^C
```

2024-11-19 20:23 UTC, Kakadu commented
> Linter report from 2024-11-19 5:56, for mini language FSharpActivePatterns
> 
> ```
> File '_build/default/lib/tests/parser.ml' doesn't have corresponding .mli interface
> File '_build/default/lib/tests/ast_printer.ml' doesn't have corresponding .mli interface
> 
> File "lib/prettyPrinter.ml", line 69, characters 39-47:
> 69 |   | Const (String_lt s) -> fprintf fmt "\"%s\"" s
>                                             ^^^^^^^^
> Alert zanuda-linter: The format string is too much verbose (rewrite "%s" -> %S)
> ```

Линтер?

2024-11-19 20:31 UTC, Kakadu requested changes
У меня генератор подвисает. ТТ

2024-11-19 20:31 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.ml
> +[@@deriving eq, show { with_path = false }, qcheck]
А почему не обычный список?

2024-11-19 20:31 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.mli
> -(** Copyright 2024-2025, Ksenia Kotelnikova <xeniia.ka@gmail.com>, Gleb Nasretdinov <gleb.nasretdinov@proton.me> *)
Удалять зачем?

2024-11-19 20:31 UTC, Kakadu commented on FSharpActivePatterns/lib/dune
> +  (pps ppx_deriving_qcheck ppx_deriving.show ppx_deriving.eq))
А вы точно пользуетесь eq?

2024-11-19 20:31 UTC, Kakadu commented on FSharpActivePatterns/lib/prettyPrinter.ml
> +  | Const (String_lt s) -> fprintf fmt "\"%s\"" s
%S

2024-11-19 21:04 UTC, p1onerka commented on FSharpActivePatterns/lib/ast.ml
> +[@@deriving eq, show { with_path = false }, qcheck]
Подумали, что так будет проще. Проще не очень получилось

2024-11-19 21:05 UTC, p1onerka commented on FSharpActivePatterns/lib/ast.mli
> -(** Copyright 2024-2025, Ksenia Kotelnikova <xeniia.ka@gmail.com>, Gleb Nasretdinov <gleb.nasretdinov@proton.me> *)
Там весь файл удаляли. Был `.mli`, стал `.ml`

2024-11-24 08:25 UTC, Ycyken commented on FSharpActivePatterns/lib/dune
> +  (pps ppx_deriving_qcheck ppx_deriving.show ppx_deriving.eq))
Да, для сравнения аст в qcheck

2024-11-26 10:46 UTC, merged