OCaml + ADT: Implement MiniML Parser
Kakadu/fp2024 pull request #46
Opened 2024-11-11 20:33 UTC by suvorovrain

2024-11-11 22:30 UTC, suvorovrain commented
ну не наказывайте за зануду ПЛИЗ
Миша завтра встанет все починит

2024-11-11 22:51 UTC, Kakadu commented
> ну не наказывайте за зануду ПЛИЗ
> Миша завтра встанет все починит

До зануды дело не дошло

2024-11-11 23:31 UTC, suvorovrain commented
Дошло

2024-11-11 23:32 UTC, suvorovrain commented
Надеюсь, если на пару часиков чуть-чуть опоздал из за небольших технических неполадок с QCheck, то это можно и простить!!!!! :smiley_cat:

2024-11-12 22:16 UTC, therain7 requested changes
- pretty принтер должен быть pretty с точки зрения расстановки скобок. Например 1 + 2 + 3, а не ((1 + 2) + 3)
- pretty принтер можно использовать и в обычных тестах на парсер, если он работает
- подозреваю, что квикчек должен что-то находить и вы должны это починить\
- у вас какой-то очень грустный генератор, да и подразумевалось, что вы его сгенерируете, а не будете писать вручную

**дедлайн 20 ноября**

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/ast_check.t
> +  ../bin/main.exe: not found
жаль

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +  | Pat_var id -> Stdlib.Format.fprintf fmt "%s" id
%s вам зачем

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +  | Const_string s -> Stdlib.Format.fprintf fmt "\"%s\"" s
%S

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +         (List.map pl ~f:(fun p -> Stdlib.Format.asprintf "%a" pprint_pattern p)))
вроде можно это не строкой приделывать. посмотрите внимательнее на `Format`

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +  | Const_integer n -> Stdlib.Format.fprintf fmt "%d" n
вы везде будете писать `Stdlib.Format`

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +      "(%a, %a%s)"
а может ex1::ex2::exl и дальше принтить список, разделив элементы запятой

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
> +    let pt1, ptl = ptl1 in
??

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/astpprinter.ml
как-то ваш pretty принтер написан не очень pretty

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/basict.ml
содержательно

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/dune
> +  (pps ppx_expect ppx_deriving.show))
show в тестах?

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/expressiont.ml
> +    Syntax error |}]
жаль

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/parser.ml
> +let%expect_test "negative int constant" =
`(*good*)`

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
вроде идея была в том, что вы будете использовать `deriving qcheck`, а не писать свои генераторы, которые можно специально случайно написать так, что они не будут генерить ничего плохого.

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +let rec gen_expression size =
скудно

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +let gen_operator_d =
e

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +open Ocamladt_lib.Ast
open QCheck.Gen

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +           else true
?

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +      ; map2
вы очень любите лифты

2024-11-12 22:16 UTC, therain7 commented on OcamlADT/tests/qcheckt.ml
> +          (fun e1 e2 -> Exp_tuple (e1, e2, []))
грустные туплы у вас какие-то. да и в целом генератор

2024-11-12 22:18 UTC, therain7 commented
и миша не встал и не починил

2024-11-16 14:11 UTC, suvorovrain commented on OcamlADT/tests/qcheckt.ml
> +let gen_operator_d =
Андрейчик (малыш) (норм чел) не пон че значит _d в конце парсера

2024-11-16 14:15 UTC, suvorovrain commented on OcamlADT/lib/parser.ml
> +*)
спасибо

2024-11-17 10:13 UTC, qrutyy commented on OcamlADT/tests/qcheckt.ml
> +let gen_operator_d =
Там это обозначало генератор операторов, которые действуют исключительно с 2 аргументами.

2024-11-20 21:25 UTC, Kakadu commented on OcamlADT/check.sh
> +opam exec -- dune runtest --instrument-with bisect_ppx --force
Вам про Makefile не рассказывали? Где вы были на 1м курсе?

2024-11-21 07:05 UTC, qrutyy commented on OcamlADT/check.sh
> +opam exec -- dune runtest --instrument-with bisect_ppx --force
Рассказывали. Это было временное решение.

2024-11-21 08:30 UTC, Kakadu commented on OcamlADT/check.sh
> +opam exec -- dune runtest --instrument-with bisect_ppx --force
Makefile --- вечен

2024-11-21 08:34 UTC, qrutyy commented on OcamlADT/check.sh
> +opam exec -- dune runtest --instrument-with bisect_ppx --force
Не спорю!

2024-11-21 10:12 UTC, suvorovrain commented
@Kakadu Можно ли продлить дедлайн на исправление новых багов до **23:59** **28.11.2024**? или хотя бы до **23:59** **25.11.2024**.

2024-11-27 20:49 UTC, therain7 approved these changes
ок

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/bin/main.ml
>    let factorial_ast : program =
не появился.

да и предназначение этого файла не очень понятно

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/ast.ml
mli?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +
а выше было все на map/lift

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/ast.ml
> +    Printf.printf "n =  %d\n\n" n;
?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/parser.ml
> +  match id with
>>| function

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/parser.ml
> +  (*todo: pass ws rework*)
when

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/parser.ml
> +      return (Expression.Exp_apply (constr, arg))
какой-то лютый костыль

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/parser.mli
> +val pseval : Structure.structure_item t
зачем это все в интерфейсе?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +  | Type_arrow (tye1, tye2) -> fprintf fmt "(%a -> %a)" pprint_type tye1 pprint_type tye2
красиво принтить типы не обязательно?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +             (List.map tyel ~f:(fun t -> asprintf "%a" pprint_type t)))
просто соедините голову с хвостом и обрабатывайте одинаково

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +     | Pat_tuple _ -> fprintf fmt "(%s (%a))" id pprint_pattern p
стремно приоритет прикручивать вручную для конкретных кейсов

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +         ^ String.concat
вы не справились это не строкой делать?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +      "(%a, %a%s)"
туплы не обязательно в скобках

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +        | _ -> fprintf fmt "not covered\n")
??

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/parser.ml
> +    Expression.Exp_apply (Exp_ident binoptoken, Exp_tuple (e1, e2, [])))
у операторов 2 аргумента по-хорошему, а не один

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
> +              second
скопировали. еще и ассоциативность угадываете по значению приоритета

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/pprinter.ml
не самая плохая попытка в pretty.
жаль только, что сам код совсем не pretty

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/tests/qcheckrun.ml
> +           let result = List.equal Poly.equal parsed_program program in
кажется, у вас должен быть нормальный eq для ast

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/tests/qcheckrun.ml
> +               "Mismatch! Original: %s\nPprinted: %s\nParsed: %s\n"
по-хорошему распечатку ошибок надо оставить кучеку

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/tests/qcheckrun.ml
> +  print_endline "Testing manual generator.";
а manual где

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/lib/tests/qcheckrun.ml
> +  let _ : int = QCheck_base_runner.run_tests [ test_round_trip2 ] in
а как оно запускаться должно?
теста на это нет. и бинаря тоже.
так еще и seed не прибит

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/tests/fact_ast_check.t
к чему это. что вы проверяете здесь

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/tests/parser.ml
> +;;
good / bad?

2024-11-27 20:49 UTC, therain7 commented on OcamlADT/tests/unittests/expressiont.ml
к чему это. если других "юнит" тестов нету, а этим все равно маловато.
чем принципиально отличается от основных тестов на парсер?

2024-11-27 20:49 UTC, merged