PPrinter + QuickCheck: OCaml + Recursive values (Viacheslav Sidorov and Danila Rudnev-Stepanyan)
Kakadu/fp2024 pull request #49
Opened 2024-11-11 20:56 UTC by xamelllion

2024-11-12 21:42 UTC, therain7 commented
Давайте я все-таки не буду это смотреть, пока вы не почините билд. И сделаете это в течение *сегодня*

2024-11-12 21:46 UTC, xamelllion commented
> Давайте я все-таки не буду это смотреть, пока вы не почините билд. И сделаете это в течение _сегодня_

В целом то оно билдится, просто quickcheck находит ошибку и тест падает (к первому дедлайну это допустимо как я понял)
Могу запуск этого теста временно отключить, тогда галочка будет

2024-11-12 22:04 UTC, xamelllion commented
ок, был не прав

2024-11-13 21:55 UTC, therain7 requested changes
- вы даже match не парсите (доделайте парсер до конца. до miniml)
- pretty принтер должен быть pretty с точки зрения расстановки скобок. Например 1 + 2 + 3, а не ((1 + 2) + 3)
- квикчек запустите нормально, найдите проблемы, исправьте

к **21 октября** все все должно быть доделано и исправлено

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/lib/ast.ml
> +  | OptSome of expression (** Some x *)
без соответствующих паттернов они не особо интересны

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    let ife = peif tuple <|> tuple in
1 + if a then b else c

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/parser.ml
>    parse_to_unit "let lie = \"i love Ocaml\"";
{| |}

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/parser.ml
> +  [%expect {| [(SValue (NonRec, [((PVar "x"), (ExprLiteral (IntLiteral 5)))]))] |}]
почему не используете свой же pretty printer?

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/quickcheck.ml
идея была в том, что вы будете использовать `deriving qcheck`, а не писать свои генераторы, которые можно специально случайно написать так, что они не будут генерить ничего плохого.

кстати пустые списки там, где их не должно быть, по-хорошему не должны быть представимы в аст

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/quickcheck.ml
> +    | _ -> true)
круто

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/quickcheck.ml
> +          ; 1, map (fun el -> ExprTuple el) (list_size (int_range 1 10) (self 0))
вы считаете правильным явно ограничивать размер тех же туплов еще в генераторе?

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/lib/parser.ml
>      choice [ pelet expr; pefun expr; ife ])
вы match не парсите и все вокруг. и приписывание типов к идентификаторам.
в общем парсер miniml к дедлайну вы не сделали все-таки

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +    let ife = peif tuple <|> tuple in
и все подобное

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/lib/parser.ml
> -(* need to add parsers for PTuple; PCons; PPoly *)
где

2024-11-13 21:55 UTC, therain7 commented on OCamlRV/tests/quickcheck.ml
> +  | Error _ -> []
норм?

2024-11-16 15:37 UTC, Dabzelos commented on OCamlRV/tests/quickcheck.ml
> +  | Error _ -> []
не совсем понятно что не устроила, поговорил со Славой оба предположили что дело в обработке ошибок, я ее сделаю, но если требуется что-то другое то расшифруй пожалуйста)))

2024-11-16 21:49 UTC, therain7 commented on OCamlRV/tests/quickcheck.ml
> +  | Error _ -> []
не думаю, что пустой список это хорошая индикация того, что произошла ошибка

2024-11-17 01:18 UTC, Dabzelos commented on OCamlRV/tests/quickcheck.ml
> +    | _ -> true)
исправил, поставил false что бы если падаем то мы знали(как я понял в этом дело)

2024-11-17 01:43 UTC, Dabzelos commented on OCamlRV/tests/parser.ml
> +  [%expect {| [(SValue (NonRec, [((PVar "x"), (ExprLiteral (IntLiteral 5)))]))] |}]
мы его используем в тестах qcheck и есть отдельный файл pprint(переименован), в котором собствнно тестируется он сам

2024-11-18 15:45 UTC, Dabzelos commented on OCamlRV/tests/parser.ml
> +  [%expect {| [(SValue (NonRec, [((PVar "x"), (ExprLiteral (IntLiteral 5)))]))] |}]
это старые тесты, есть тесты с прити принтером, не думаю что надо их убирать,
они помогают смотртеь что поломали при правках, (например я сейчас пытаюсь починить что бы выражения по типу 1 + if парсились), так что считаю полностью обоснованным не убирать тесты которые тем более уже ревьюились много раз тк это старый файл. 
много разлиных тестов хорошо(мое мнение)

2024-11-19 00:44 UTC, Dabzelos commented on OCamlRV/lib/parser.ml
> -(* need to add parsers for PTuple; PCons; PPoly *)
Парсер тупла, Cons, точно есть. И он же есть как паттернЮ и они же есть в pretty printer

2024-11-20 18:50 UTC, xamelllion commented on OCamlRV/lib/ast.ml
> +  | OptSome of expression (** Some x *)
Добавил соответствующие паттерны

2024-11-20 18:54 UTC, xamelllion commented on OCamlRV/tests/quickcheck.ml
quickcheck переделал, для tuple указал размер >= 2

2024-11-20 18:55 UTC, xamelllion commented on OCamlRV/lib/parser.ml
> -(* need to add parsers for PTuple; PCons; PPoly *)
PTuple добавил

2024-11-23 22:10 UTC, xamelllion commented on OCamlRV/lib/parser.ml
>      choice [ pelet expr; pefun expr; ife ])
типы добавили

2024-11-25 11:30 UTC, therain7 requested changes
![image](https://github.com/user-attachments/assets/dd043e11-4d43-4b1b-a1cd-43a789700642)

`pretty принтер должен быть pretty с точки зрения расстановки скобок. Например 1 + 2 + 3, а не ((1 + 2) + 3)`
**не сделали**

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/Pprintast.ml
> +       | _ -> fprintf ppf "%a::%a" helper p1 helper p2)
это очень стремно, т.к.
1. есть общее решение для расстановки скобок. здесь пытаетесь рассмотреть все случаи вручную, что сам должны понимать, почему плохо может быть
2. загуглите or паттерны

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/Pprintast.ml
ваш подход к расстановке скобок оставляет желать лучшего.
при том, что я скидывал вам же в чат, как это делать в общем случае

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/ast.ml
> +  | BoolLiteral of (bool[@gen QCheck.Gen.bool])
qcheck сам может догадаться, как генерить bool

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/ast.ml
> +        [@gen QCheck.Gen.(list_size (0 -- 10) (gen_binding_sized (n / div)))])
а в других местах генератор делит на 2

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/ast.ml
>    | SEval of expression
а какая глубина по умолчанию?

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  list_type
короче

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/lib/parser.ml
> +  | [] -> ExprOption None (* unreachable *)
сомнительное дефолтное значение для такого.
тут можно спорить, что стоит делать в таком случае, но вариантов не очень много

2024-11-25 11:30 UTC, therain7 commented on OCamlRV/tests/quickcheck.t
> +  $ ../tests/quickcheck.exe -seed 342723456 -gen 1
1 запуск?

2024-11-25 11:30 UTC, therain7 commented
и линтер не поправили

2024-11-25 11:31 UTC, merged