Go: Add parser and qcheck (Karim Shakirov, Alexei Dmitrievtsev)
Kakadu/fp2024 pull request #50
Opened 2024-11-12 14:38 UTC by shakareem

- add parser for required subset of go
- add unit tests for the parser

- Qcheck test can be ran with 
```shell
dune exec ./_build/default/tests/parser/qCheck/qCheckRun.exe
```

2024-11-12 15:06 UTC, Kakadu commented
Я думаю, что за такое пользование гитом надо ставить **жирный минус**

2024-11-12 21:38 UTC, therain7 requested changes
А я думаю, что содержание важнее навыков пользования гитом @Kakadu .

- оно не билдится
- pretty принтер должен быть pretty с точки зрения расстановки скобок ( например 1 + 2 + 3 а не ((1 + 2) + 3)
- pretty принтер можно использовать и в обычных тестах на парсер, если он работает
- подозреваю, что квикчек должен что-то находить и вы должны это починить

если у вас все-таки не **жирный минус**, а возможный плюс, то дедлайн **13 ноября**

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> +  | Const_func of anon_func (** See anon_func type *)
интересно

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> -  | Expr_nil (** A value of an unitialized channel or function: [nil] *)
куда nil

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      for multiple identifiers such as [var a, b, c = get_three()].
только function call? по типу - не только

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> +and short_var_decl =
это никак не объединяется с тем, что выше?

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      }
можно variant type засунуть внутрь рекорда. может аккуратнее будет выглядеть

2024-11-12 21:38 UTC, therain7 commented on Go/lib/ast/ast.ml
> +      [a, b, c[i] = get_three()] . Invariant: size of the list >= 1 *)
время задуматься, правда ли вы хотите все это поддерживать

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/dune
> + (modules Common Expr Stmt TopLevel Parse)
можно не перечислять

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/parse.ml
попробуйте назвать его `parser.ml` и посмотреть, что будет

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/parse.ml
> +let parse parser str = Angstrom.parse_string ~consume:Angstrom.Consume.All parser str
eta?

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/common.ml
> +let sep_by_comma p = sep_by (token ",") p
eta?

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/common.ml
> +  let* first_char = peek_char in
satisfy?

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/common.ml
> +  let determine_direction =
parse_direction
pdirection

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/expr.ml
> +    >>= (fun new_oper -> helper (fun expr -> acc @@ new_oper @@ expr))
последнее @@ не нужно

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/expr.ml
> +let parse_idents_with_types =
не хватает док комментов с синтаксисом того, что парсите

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/expr.ml
> +       let* char = ws_line *> peek_char_fail in
зачем peek

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/expr.ml
> +    arg)
последний let можно выкинуть

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/expr.ml
> +    let arg = chainl1 arg (parse_sum <|> parse_subtraction) in
надеюсь, что приоритет здесь расставлен не наугад

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/parse.ml
возможно не стоит

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +;;
посмотрите на `List.map2_exn` / `List.map2`

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +    | None -> fail "Long variable declaration without initializers should have type")
в силу особенности работы angstrom, эти сообщения пользователь не увидит никогда скорее всего

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +    then fail "No identifiers in long variable declaration"
`let* () = if List.is_empty lvalues then fail "?" else return () in`
так можно избавиться от такой вложенности

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +             or rvalue should be a function that returns multiple values"
как-то стремно очень это все выглядит

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +         initializer is not a single function with multiple returns"
и это тоже. if else if else if else if else FAIL

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +  match expr with
function

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +  let ok_post = if is_valid_init_and_post init then true else false in
??

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +  then fail "Incorrect statement in for initialization or post statement"
как-то очень сишно это выглядит все.
вам правда необходимо столько проверок?
если да, то уберите большую вложенность хотя бы

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +       })
не понял. откуда i взялось

2024-11-12 21:38 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +      | [] -> assert false
сюда бы fail из строчки выше да

2024-11-12 21:38 UTC, therain7 commented on Go/tests/parser/qCheck/astGenerator.ml
вроде идея была в том, что вы будете использовать `deriving qcheck`, а не писать свои генераторы, которые можно специально случайно написать так, что они не будут генерить ничего плохого.

кстати пустые списки там, где их не должно быть, по-хорошему не должны быть представимы в аст

2024-11-12 21:38 UTC, therain7 commented on Go/tests/parser/qCheck/qCheckRun.ml
ну тут верим, что работает

2024-11-12 21:38 UTC, therain7 commented on Go/tests/parser/unitTests/commonTest.ml
> +    (Type_chan (Chan_send (Type_chan (Chan_bidirectional Type_int)))) |}]
а где *pretty* printer ваш

2024-11-13 11:02 UTC, shakareem commented on Go/tests/parser/qCheck/astGenerator.ml
А что не так с тем, чтобы прописать инварианты и следовать им в парсере и генераторе?

2024-11-13 11:30 UTC, Kakadu commented on Go/tests/parser/qCheck/astGenerator.ml
Вот если бы вы ходили на лекции, то не задавали бы такие вопросы.

2024-11-13 12:08 UTC, shakareem commented on Go/lib/ast/ast.ml
> -  | Expr_nil (** A value of an unitialized channel or function: [nil] *)
nil - предопределенный идентификатор, такого экспрешена нет

2024-11-13 12:13 UTC, shakareem commented on Go/lib/ast/ast.ml
> +and short_var_decl =
нет, short decl используется только в стейтментах, а long и в стейтментах и в top decl

2024-11-13 12:13 UTC, shakareem commented on Go/lib/ast/ast.ml
> +      }
рил

2024-11-13 13:19 UTC, therain7 commented on Go/lib/ast/ast.ml
> -  | Expr_nil (** A value of an unitialized channel or function: [nil] *)
лан

2024-11-13 13:20 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +       })
в случае `for range 1000 {}` идентификатор i должен быть доступен в теле?

2024-11-13 13:33 UTC, Kakadu commented on Go/lib/parser/stmt.ml
> +       })
Ох, как же вас quickcheck расстроит

2024-11-13 15:16 UTC, shakareem commented on Go/lib/parser/stmt.ml
> +       })
> в случае `for range 1000 {}` идентификатор i должен быть доступен в теле?

Нет, но в чем проблема?

2024-11-13 18:43 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +       })
ну видимо в вашем случае будет

2024-11-13 20:41 UTC, shakareem commented on Go/lib/parser/parse.ml
> +let parse parser str = Angstrom.parse_string ~consume:Angstrom.Consume.All parser str
Вылетает ошибка. Кажется из-за [этого](https://discuss.ocaml.org/t/partial-application-and-weak1-type-variable-that-cannot-be-generalized/5512).

2024-11-13 20:42 UTC, shakareem commented on Go/lib/parser/common.ml
> +let sep_by_comma p = sep_by (token ",") p
Так жеб как в предыдущем случае

2024-11-13 21:07 UTC, therain7 commented on Go/lib/parser/parse.ml
> +let parse parser str = Angstrom.parse_string ~consume:Angstrom.Consume.All parser str
мб вам не нужна такая полиморфная функция

2024-11-13 22:21 UTC, shakareem commented on Go/lib/parser/stmt.ml
> +       })
ааа понял

2024-11-14 11:20 UTC, shakareem commented on Go/lib/parser/stmt.ml
> +;;
а что делать с исключением? Вместо ```('a * 'b) list```` получается тип ```('a * 'b) list Base.List.Or_unequal_lengths.t```

2024-11-14 17:05 UTC, therain7 commented on Go/lib/parser/stmt.ml
> +;;
если вы уверены, что не может быть unequal lengths, то используйте `_exn`

2024-11-20 21:13 UTC, therain7 commented
<img width="488" alt="image" src="https://github.com/user-attachments/assets/c28bbbab-2340-4c05-bc4f-f37c97b066bb">
почините :(

2024-11-21 16:15 UTC, therain7 commented
![image](https://github.com/user-attachments/assets/c32b6081-e35f-4061-bb5d-4c9f6d2e9949)
не помогло

2024-11-21 17:06 UTC, Kakadu commented
> ![image](https://github.com/user-attachments/assets/c32b6081-e35f-4061-bb5d-4c9f6d2e9949)
> не помогло. и зануда ругается

Там гипотетически может быть ложное срабатывание, но мне казалось что такого рода я все извел

2024-11-21 21:32 UTC, shakareem commented
Я справился

2024-11-21 21:37 UTC, shakareem commented
Если я правильно понял, зануда ругается на использование на что-то вроде ```match ... | ... -> if ...```, я всё проверил, у нас такого нет

2024-11-25 11:02 UTC, therain7 approved these changes
видно, что старался/ись

2024-11-25 11:02 UTC, therain7 commented on Go/tests/parser/qCheck/astGenerator.ml
> +let size4 = int_range 0 4
у вас сомнительный подход к глубине генерации какой-то

2024-11-25 11:02 UTC, therain7 commented on Go/tests/parser/qCheck/astGenerator.ml
тут видимо верим, что генерится все, что хочется и не хочется

2024-11-25 11:02 UTC, therain7 commented on Go/tests/parser/qCheck/astGenerator.ml
> +let size4 = int_range 0 4
если поставить int_range 0 10, то видимио можно долго ждать

2024-11-25 11:02 UTC, merged

2024-11-25 11:32 UTC, shakareem commented on Go/tests/parser/qCheck/astGenerator.ml
> +  sized_size size4
Иначе виснет

2024-11-25 11:35 UTC, shakareem commented on Go/lib/ast/ast.ml
> +and if_for_init =
Всё ради того, чтобы некорректные с точки зрения синтаксиса программы не были представимы в аст

2024-11-25 11:38 UTC, shakareem commented on Go/lib/parser/common.mli
> +val ws_line : unit t
вайтспейс в пределах одной строки, по спецификации в некоторых местах следующая синтаксическая единица должна быть на той же строке, между ними может быть сколько угодно пробелом, табов и блок комментов

2024-11-25 11:38 UTC, shakareem commented on Go/lib/parser/stmt.ml
> +;;
мне не понравился эксепшон

2024-11-25 22:55 UTC, Kakadu commented on Go/a.out
Кириленко подтвердил, что за такое ставят минус)