Go: Add Typechecker (Aleksei Dmitrievtsev, Karim Shakirov)
Kakadu/fp2024 pull request #55
Opened 2024-12-09 20:06 UTC by admitrievtsev

Implemented Go-minilang typechecker that checks:
- Multiple declarations (all idents, func and var)
- Using of undefined ident
- Returns, args and existence of main func
- Mismatched types (func returns and args, binary operations etc.)

_Немного замечаний к своей же работе, которые планируется исправить на следующей неделе ~~чтобы проверяющие не писали лишний раз очевидные замечания~~_
- Убрать мусор в тестах, который не несет смысловой нагрузки
- Вынести тесты в соответствующую директорию
- Убрать некоторые пустые по своей сути функции наподобие *seek_ident*, которые остались с ранних версий и должны быть замещены в самое ближайшее время 
- Доделать несколько пунктов с пометкой (*доделать*) в коде. Они, как правило, не относятся к очевидной базовой функциональности, также мы обсудим с коллегой целесообразность поддержки некоторых из них.
- Более содержательные сообщения об ошибках
- Подумать как убрать кринж наподобие (List.combine (x :: y :: z) (List.map (fun _ -> Expr_call l) (x :: y :: z)))) _С одной стороны, это моя гордость, "родить" такое удается далеко не каждый день._

2024-12-13 09:21 UTC, Kakadu commented on Go/lib/typecheck/typeCheckMonad.ml
> +  ;;
Format.pp_print_list ~sep ?

2024-12-15 17:54 UTC, therain7 requested changes
я не понял алгоритма проверки типов с двумя каким-то странными env.
и код написан так, что сразу совсем не понятно, а разбираться не особо хочется)
без негатива, но поясните. либо здесь, либо докой

а еще доделайте, что нужно доделать. у вас ~неделя

2024-12-15 17:54 UTC, therain7 commented on Go/a.out
finally

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckErrors.ml
> +  | Check_failed
это что

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckErrors.ml
> +  | Cannot_assign of ident
документацию

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +module BaseMonad = struct
стоит написать, что это state + result

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +type type_check = global_env * local_env * current_func option
сомнительный кейс использования type алиасов.
лучше соответствующие поля в структурах, непосредственно участвующих в процессе.
тем более здесь например global и local env - одно и то же

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +  let retrieve_paris_second args = List.map (fun (_, x) -> x) args
париж

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +  let retrieve_paris_second args = List.map (fun (_, x) -> x) args
fun args -> f args

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +  let retrieve_paris_second args = List.map (fun (_, x) -> x) args
и названия можно попроще

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +    match x with
function

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +      (match x with
сомнительный shadowing имени

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +    | global, _, _ -> return global
может лучше record, а не tuple

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
> +  ;;
лучше рекорд

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.ml
нужен .mli на это с тем, что реально используется. и как-то многовато boilerplate-а в целом.
попробуйте что ли сделать некоторые функции более полиморфными.
и замените местами туплы на рекорды

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +let retrieve_anon_func x =
кажется, я это уже видел

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +      (TypeCheckError
это что-то стремное. кажется, что надо сначала протайпчекать весь модуль, получить все типы, а потом уже просто посмотреть в env

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +  match x with
function

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +        | _ -> return (Type_func (x, y)))
pattern matching по листу сразу делайте

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +    if retrieve_type_expr y = return Type_int
bind?

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +    | Glob -> save_global_ident_l
я ниче не понял, как у вас env работает.
кажется, он должен мапить идентификаторы на типы, но тут что-то странное

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +         ((x, z) :: y)
это не очень читаемо. особенно с такими названиями

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +       if retrieve_type_expr (Expr_call l) != return k
сравнивать значения, запакованные в монаду - странный подход. особенно через polymorphic compare.
у вас bind есть

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +       then fail (TypeCheckError (Mismatched_types (Printf.sprintf "%s" (print_type k))))
Mismatched_types пусть лучше содержит не текст, а непосредственно типы, которые не сошлись, чтобы потом можно было уже как угодно их запринтить.

и зачем нужен `TypeCheckError` я не понял

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +         | true -> return (List.combine x y)
может лучше не вызывать лишний раз length, а сделать сразу combine, а потом словить exception.
либо перейти на base, там есть такое же но без экспешнов

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +     >>= iter (fun (x, y) -> retrieve_type_expr x >>= fun type1 -> check_eq y type1))
```>>= check_eq y```

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +       prerr_string x)
это здесь должно быть?

2024-12-15 17:54 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +    ];
это не читаемо, используйте парсер

2024-12-18 18:11 UTC, admitrievtsev commented on Go/a.out
Да, доку распишу к новому дедлайну. Не стал докментировать текущаю версию, потому что понимал, что часть основной логики изменится (уже изменилась)

2024-12-18 18:15 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckErrors.ml
> +  | Cannot_assign of ident
будет.

2024-12-18 18:16 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.ml
> +type type_check = global_env * local_env * current_func option
Сейчас уже global и local env'ы это не одно и тоже. Написал так с прицелом на будущее, прицел себя оправдал.

2024-12-18 18:17 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.ml
> +  let retrieve_paris_second args = List.map (fun (_, x) -> x) args
> париж

ай лов пэрис эври момэнт

2024-12-18 18:18 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.ml
> +      (match x with
Ага, там много такого, сяду завтра поменяю

2024-12-18 18:18 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.ml
okay

2024-12-18 18:19 UTC, admitrievtsev commented on Go/lib/typecheck/typeChecker.ml
> +      (TypeCheckError
реал

2024-12-18 18:21 UTC, admitrievtsev commented on Go/lib/typecheck/typeChecker.ml
> +    | Glob -> save_global_ident_l
Это говнокод потому что я не смог в замыкания, к дедлайну поправлю

2024-12-22 13:43 UTC, shakareem commented
@therain7 Товарищ Сухарев посмотрите пожалуйста

2024-12-25 12:22 UTC, therain7 requested changes
еще поправите немного, будет приемлимо

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.mli
> +type env = ctype MapIdent.t list
Зачем вам стек мап, если у вас есть call stack.
Вызываете функцию проверки внутреннего выражения, передаете мапу в аргументе например (можно state/reader monad). После выхода из вызова у вас услосвно остается мапа, которая не была модифицирована в вызове.

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.mli
> +  | Ctuple of Ast.type' list (** Used to check multiple returns of a function *)
что это значит

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.mli
> +  val run : 'a t -> state -> state * ('a, Errors.error) Result.t
это можно includ-ить из BaseMonad, если правильно ее написать.
Например через функторы

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeCheckMonad.mli
> +  val print_type : ctype -> string
Это не относится к monad

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +  *> delete_env
если бы вы осилили reader monad.
возможно state monad вам вообще не нужно в этом плане

2024-12-25 12:22 UTC, therain7 commented on Go/lib/baseMonad/baseMonad.ml
> +let iter2 f list1 list2 =
не хорошо, что оно кидает exception

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +     *> iter save_top_decl_funcs file
в Go можно ссылаться на еще "ниже" функции?

2024-12-25 12:22 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +let rec retrieve_expr cstmt = function
кажется, это просто `check_expr`

2025-01-14 07:54 UTC, admitrievtsev commented on Go/lib/baseMonad/baseMonad.ml
> +let read st = return st st
чеее андрей так же не работает

2025-01-14 07:57 UTC, admitrievtsev commented on Go/lib/errors/errors.ml
> +  | Check_failed (*Inner error to match errors inside typechecker*)
> что это значит

Чтобы детектить ошибки которые вылезают по причине внутренних багов в тайпчекере, наверное нужно пометить как DevOnly. Использовал чтобы оперативно отлавливать некорректное поведение.

2025-01-14 08:05 UTC, admitrievtsev commented on Go/lib/errors/errors.ml
> +  | Mismatched_types of string (*Mismatched types in binoper/assign/return...*)
Да, я помню, однако в ошибке должен быть ctype, чтобы сообщения можно было делать достаточно содержательными, а там вылезает циклическая зависимость. Можно было бы сесть подумать и как-нибудь реструктурировать проект, но это точно не то чем стоит заниматься, когда есть более приоритетные задачи (НАПИСАНИЕ ИНТЕРПРЕТАТОРА НАПРИМЕР АХАХА), поэтому пока пусть будет так, если время останется, то сделаю че-нибудь красивое. А так с замечанием полность согласен

2025-01-14 08:07 UTC, admitrievtsev commented on Go/lib/ppType/dune
> целая либа под это?

Чтобы можно было переиспользовать и в тестах, и в тайпчекере и опционально в интерпретаторе если нужно будет

2025-01-14 08:18 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.ml
> +    match List.find_opt (fun map -> MapIdent.mem ident map) env with
> fun x -> f x
ой)

2025-01-14 08:27 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.mli
> +  | Ctuple of Ast.type' list (** Used to check multiple returns of a function *)
> что это значит

Специальные типы тайпчекера, которые нужны для того чтобы протайпчекать multiple returns, дженерики которые не дженерики, например make(T, args) и так далее

2025-01-14 08:30 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.mli
> +type env = ctype MapIdent.t list
> Зачем вам стек мап, если у вас есть call stack. Вызываете функцию проверки внутреннего выражения, передаете мапу в аргументе например (можно state/reader monad). После выхода из вызова у вас услосвно остается мапа, которая не была модифицирована в вызове.

Да, действительно, можно было бы сделать так, и это выглядит красивее, но сейчас переписывать таким образом = потерять полдня, которые можно посвятить интерпретатору

2025-01-14 08:30 UTC, admitrievtsev commented on Go/lib/typecheck/typeCheckMonad.mli
> +type env = ctype MapIdent.t list
> > Зачем вам стек мап, если у вас есть call stack. Вызываете функцию проверки внутреннего выражения, передаете мапу в аргументе например (можно state/reader monad). После выхода из вызова у вас услосвно остается мапа, которая не была модифицирована в вызове.
> 
> Да, действительно, можно было бы сделать так, и это выглядит красивее, но сейчас переписывать таким образом = потерять полдня, которые можно посвятить интерпретатору

Если после горутин останется время, в чем я конечно сомневаюсь, переделаю так

2025-01-14 08:35 UTC, admitrievtsev commented on Go/lib/typecheck/typeChecker.ml
> +  *> delete_env
> если бы вы осилили reader monad. возможно state monad вам вообще не нужно в этом плане
На этапе первоначального проектирование state monad показалась самым приемлемым решением, может быть через reader было бы лучше, да. Проектировать что угодно с помощью монад в первый раз это не самое приятное ощущение, отсюда и вылезли многие проблемы

2025-01-14 11:02 UTC, shakareem commented on Go/lib/typecheck/typeChecker.ml
> +      (match check_return afunc.body with
почему-то локально зануда на это не ругается

2025-01-14 19:59 UTC, therain7 commented on Go/lib/baseMonad/baseMonad.ml
> +let read st = return st st
ок ок

2025-01-14 19:59 UTC, therain7 commented on Go/lib/errors/errors.ml
> +  | Mismatched_types of string (*Mismatched types in binoper/assign/return...*)
ок

2025-01-14 20:13 UTC, therain7 requested changes
похоже, что ваш тайпчекер построен на костылях.
давайте я не буду тыкать в каждую стремную функцию, а просто скажу, что в целом _приемлимо_, учитывая все остальное

тем не менее разберитесь уже, что такое `Check_failed`

2025-01-14 20:13 UTC, therain7 commented on Go/lib/typecheck/typeChecker.ml
> +  | _ -> asprintf "WTF Polymorphic type"
ок

2025-01-14 20:51 UTC, admitrievtsev commented on Go/lib/errors/errors.ml
> +  | Check_failed
> так почему это осталось, если это dev @admitrievtsev

выпилил

2025-01-15 09:37 UTC, therain7 approved these changes
сойдет

2025-01-15 09:38 UTC, merged