OCaml + Recursive Values infer by SIDOROV + Rudnev-Stepanyan
Kakadu/fp2024 pull request #56
Opened 2024-12-09 20:25 UTC by Dabzelos

2024-12-13 13:09 UTC, therain7 requested changes
Вроде неплохо.
Кажется, у вас около недели ~20 декабря, чтобы доделать все, что надо доделать

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +        let* sub = Subst.unify (list_type t1) t2 in
наверное это можно не делать

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +      | _ -> fail `Pattern_matching_error
это что

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +    let rec helper env = function
зачем здесь helper

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +    let rec helper env = function
и здесь зачем helper

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +           return (sub, Subst.apply sub t2))
подумайте

2024-12-13 13:09 UTC, therain7 commented on OCamlRV/lib/infer.ml
> +  ;;
ну в целом все, что выше, похоже на правду.
наверное писать это можно аккуратнее. например несколько пустых строк помогли бы читать некоторые кейсы, но ок.

2024-12-19 22:12 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +         | None -> fail (`No_variable x))
Поправил

2024-12-19 22:12 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +           return (sub, Subst.apply sub t2))
Вроде что-то придумали

2024-12-19 22:14 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +module R : sig
Renamed

2024-12-19 23:04 UTC, xamelllion commented on OCamlRV/lib/typedtree.ml
Больше не используется, удалил

2024-12-19 23:05 UTC, xamelllion commented on OCamlRV/lib/typedtree.ml
> +  | TList of ty (** List type *)
Поправил, вроде даже красиво

2024-12-19 23:13 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +  type t = ty
Вообще убрал

2024-12-19 23:15 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +  ;;
От этого тоже избавился

2024-12-19 23:18 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +    | TTuple tl -> Base.List.exists tl ~f:(occurs_in v)
Base убрал

2024-12-19 23:25 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +type fresh = int
В общем то ничем, вынес в аст

2024-12-19 23:29 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +      | other -> other
Поправил

2024-12-19 23:30 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +  let compose_all ss =
Убрал

2024-12-19 23:34 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +  type t = scheme
Сделал

2024-12-19 23:34 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +module Infer = struct
А, чет не подумал да

2024-12-19 23:36 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +module Infer = struct
Поправил

2024-12-19 23:39 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +    let rec helper env = function
Поправил

2024-12-19 23:40 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +    let rec helper env = function
Поправил

2024-12-19 23:42 UTC, xamelllion commented on OCamlRV/lib/typedtree.ml
> +  ]
pattern matching error убрал

2024-12-19 23:54 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
> +    S (xs, Subst.apply s2 t)
Не особо понял, но немного переименовал

2024-12-19 23:57 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +      | _ -> fail `Pattern_matching_error
Больше нет

2024-12-20 00:16 UTC, xamelllion commented on OCamlRV/lib/infer.ml
> +        let* sub = Subst.unify (list_type t1) t2 in
Не особо понял что не так

2024-12-25 14:44 UTC, therain7 approved these changes
в целом норм, придираться не хочу.
единственное, у вас формально не полностью мини мл покрыт, но ок сойдет пока.
доделывайте до экза

2024-12-25 14:44 UTC, therain7 commented on OCamlRV/lib/ast.ml
> +  | ATuple of type_annot list
может инвариант

2024-12-25 14:44 UTC, therain7 commented on OCamlRV/lib/inferCore.ml
mli?

2024-12-25 14:44 UTC, therain7 commented on OCamlRV/lib/inferCore.ml
> +  [ `Occurs_check
что в чем

2024-12-25 14:44 UTC, therain7 commented on OCamlRV/lib/inferCore.ml
> +  | `Not_implemented
этого быть не должно, напоминаю

2024-12-25 14:44 UTC, therain7 commented on OCamlRV/lib/infer.mli
> +  -> ( (string, InferCore.Scheme.t, Base.String.comparator_witness) Base.Map.t
TypeEnv.t?

2024-12-25 14:44 UTC, merged

2024-12-29 20:46 UTC, xamelllion commented on OCamlRV/lib/infer.mli
> +  -> ( (string, InferCore.Scheme.t, Base.String.comparator_witness) Base.Map.t
Поправил

2024-12-29 20:46 UTC, xamelllion commented on OCamlRV/lib/inferCore.ml
Добавил

2024-12-29 20:46 UTC, xamelllion commented on OCamlRV/lib/ast.ml
> +type fresh = int [@@deriving show { with_path = false }, qcheck]
Поправил