Add type checker for OCaml bidirectional records. Sophia Kozyreva, Maksim Shipilov
Kakadu/fp2024 pull request #58
Opened 2024-12-09 20:54 UTC by mshipilov5

inferencer at lib/inferencer.ml

2024-12-13 13:12 UTC, therain7 commented
теперь тут что-то сломано

2024-12-13 15:37 UTC, therain7 commented
@mshipilov5 @sofyak0zyreva почините

2024-12-13 19:26 UTC, therain7 requested changes
доделывайте
у вас ~неделя

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/typedtree.ml
> +(* actual types *)
это те же самые, что в AST. буквально одно и то же.
зачем вы все делаете это отдельными структурами, а потом пытаетесь как-то привести одну к другой

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/parser.ml
> +  pstoken ":" *> (some_type >>| fun t -> Some t) <|> return None
там еще скобки зачастую обязательны

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/typedtree.ml
> +  | `Occurs_check -> Format.fprintf ppf {|Occurs check failed|}
было бы полезно знать, что в чем occurs

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.mli
> +  val infer_program_test : string -> unit
если test, то и должно быть в тестах

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +module R : sig
что значит R?

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  let rec occurs_in v = function
чуть проще и может менее эффективно будет собрать free vars, а потом проверить на вхождение

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +    | TVar b -> b = v
почему b

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  let compose_all subs_list = RList.fold_left subs_list ~init:(return empty) ~f:compose
наверное это списано

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  ;;
зачем вам `function`

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  open R
уже было

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +     ;; *)
??

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +      | _ -> fail (`Undefined_variable "Unhandled case in `infer`")
этого быть не должно

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +    | Ast.SValue (Non_recursive, Evalue_binding (id, expr), other_bindings) ->
а почему не приклеить голову к other_bindings

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  ;;
этого здесь быть не должно

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +      | Etuple (e1, e2, es) ->
e1::e2::es
вы выше так умели, а здесь уже разучились

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +  let w expr = Result.map snd (run (infer TypeEnv.empty expr))
верим, что все, что выше, работает корректно.
но на самом деле пока не верим, но верим, что тесты прояснят

2024-12-13 19:26 UTC, therain7 commented on OcamlBR/lib/inferencer_tests.ml
скудно, очень

2024-12-13 20:10 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +     ;; *)
не успели заиспользовать в infer (Efun)

2024-12-13 20:11 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +    | TVar b -> b = v
b -- **bound** inside TVar

2024-12-13 20:13 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +module R : sig
result, но как бы custom: дополнительно храним информацию о переменных

2024-12-15 11:15 UTC, Kakadu commented on OcamlBR/lib/ast.ml
> +  | Eprint_int of (expr[@gen gen_expr_sized (n / divisor)])
https://github.com/Kakadu/fp2024/blob/master/tasks.md
перечитайте

2025-01-20 03:06 UTC, mshipilov5 commented
> Linter report from 2025-01-20 5:54, for mini language OcamlBR
> 
> ```
> File "_none_", line 1:
> Alert zanuda-linter: Prefer guard instead of if-then-else in case construction
> ```

В ручную были просмотрены все if, ни один не лежит внутри case конструкций

2025-01-29 16:58 UTC, therain7 requested changes
пока хватит

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/ast.ml
> +  | Econstraint of (expr[@gen gen_expr_sized (n / divisor)]) * (ty[@gen gen_tprim])
PConstraint и вам не нужен хак с ty_pattern

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer_tests.ml
> +  result
сделайте cram на repl

2025-01-29 16:58 UTC, therain7 commented on manytests/do_not_type/097fun_vs_unit.ml
кажется, этого не должно быть в PR

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/repl/repl.ml
> +    ; inference = false
странные значения по умолчанию

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/repl/repl.ml
> +     | SA_never ->
т.е. два этапа в интерпретаторе

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/typedtree.mli
> +  | `Ill_right_hand_side of string
что это

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/typedtree.ml
> +  | `Occurs_check -> Format.fprintf ppf {|Occurs check failed|}
заигнорили коммент выше

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer_tests.ml
> +  [%expect {|  |}]
где

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +        compose acc s)
f1 :: s1 :: rest1

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +      validate_field_type env t2
к чему это в этом PR

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +      (* Format.printf "(Subst.apply subst1 t_pat): %a\n" pp_ty (Subst.apply subst1 t_pat); *)
к чему эти принты здесь в пр

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +            | Ast.Evalue_binding ((p, opt_ty), expr) ->
перенесите pattern matching в fun ->

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/inferencer.ml
> +          in
код лестницой

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/ast.ml
> +      * (pattern[@gen gen_pattern_sized (n / divisor)])
это одно и то же да

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/values.ml
> +  | VBuiltin of builtin * environment
зачем с билтином хранить окружение

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +    if List.length l1 <> List.length l2
fold2 умеет об этом сообщать сам

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +  ;;
кажется это что-то тайпчека

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +      return (VTuple (v1, v2, List.rev v_rest))
map придумали?

2025-01-29 16:58 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +            return VUnit
хардкод или не хардкод

2025-01-29 17:23 UTC, sofyak0zyreva commented on OcamlBR/lib/typedtree.mli
> +  | `Ill_right_hand_side of string
Отметаем некорректные паттерны: например, let 0 = 1, let rec (a, b) = <..> -- `Ill_left_hand_side. а let rec x = x + 1 -- `Ill_right_hand_side. Т.к. ошибки of string, там поясняющие комментарии указаны

2025-01-29 17:24 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer_tests.ml
> +  [%expect {|  |}]
здесь нет svalue (let a = <..>), так что и нечему присваивать тип по-хорошему

2025-01-29 17:33 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +    if List.length l1 <> List.length l2
вроде как fold_left2 выбрасывает исключение

2025-01-29 17:40 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +  ;;
вроде бы let (0, b) = (4, 3) формально тайпчек проходит, но Warning 8: this pattern-matching is not exhaustive выбрасывается. Здесь просто отсеиваются случаи, когда не переменные слева. насчет validate_pattern_rec согласна, его можно и убрать

2025-01-29 17:55 UTC, therain7 commented on OcamlBR/lib/typedtree.mli
> +  | `Ill_right_hand_side of string
я понимаю да, но нет документации к конструктору как минимум

2025-01-29 17:56 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +    if List.length l1 <> List.length l2
в Base точно есть тот, что не выбрасывает.
да и можно половить исключения

2025-01-29 17:57 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +  ;;
так а что не так с `let (0, b) = (4, 3)`

2025-01-29 18:04 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +      return (VTuple (v1, v2, List.rev v_rest))
с кем не бывает:) хотя не вижу ничего страшного

2025-01-29 18:18 UTC, sofyak0zyreva commented on OcamlBR/lib/ast.ml
> +      * (pattern[@gen gen_pattern_sized (n / divisor)])
+- да

2025-01-31 03:20 UTC, mshipilov5 commented on OcamlBR/lib/inferencer_tests.ml
> +  result
сделали! tests/run.t

2025-01-31 11:42 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +  ;;
на этапе тайпечка ничего, но интерпретатор по сути не должен это принимать, т.к. pattern-matching is not exhaustive

2025-01-31 11:46 UTC, sofyak0zyreva commented on OcamlBR/lib/values.ml
> +  | VBuiltin of builtin * environment
оказалось ненужным, убрала

2025-01-31 11:46 UTC, sofyak0zyreva commented on OcamlBR/lib/typedtree.ml
> +  | `Occurs_check -> Format.fprintf ppf {|Occurs check failed|}
поправили

2025-01-31 11:49 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +      (* Format.printf "(Subst.apply subst1 t_pat): %a\n" pp_ty (Subst.apply subst1 t_pat); *)
убрали

2025-01-31 11:49 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +          in
поправила

2025-01-31 11:49 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +            | Ast.Evalue_binding ((p, opt_ty), expr) ->
сделали

2025-01-31 12:26 UTC, sofyak0zyreva commented on OcamlBR/lib/inferencer.ml
> +        compose acc s)
переделали

2025-02-14 05:27 UTC, therain7 requested changes
тестируйте интерпретатор отдельно от инфера.
и проверьте такое на нем `let f () = y in let y = 42 in f ()`

2025-02-14 06:07 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +      return (VTuple (v1, v2, List.rev v_rest))
я пробовала, но он выглядит не очень аккуратно из-за "распаковки" переменной, можно так оставим?

2025-02-14 06:09 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +      then fail (`Ill_left_hand_side "Pattern not acceptable for variable name")
вроде уже выше обсуждали, зачем оно тут

2025-02-14 08:13 UTC, therain7 commented on OcamlBR/lib/interpreter.ml
> +  ;;
т.к. match failure

2025-02-14 09:49 UTC, sofyak0zyreva commented on OcamlBR/lib/ast.ml
> +      * (pattern[@gen gen_pattern_sized (n / divisor)])
имеется в виду, что в обоих случаях парсится лист, только в первом паттерн будет выглядеть как [7; 5] или [], а во втором  h::tl, h::m::tl

2025-02-14 11:38 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +    | Elet (Recursive, Evalue_binding (pat, e1), [], e2) ->
убрала

2025-02-14 11:38 UTC, sofyak0zyreva commented on OcamlBR/lib/interpreter.ml
> +      then fail (`Ill_left_hand_side "Pattern not acceptable for variable name")
теперь доходит

2025-02-14 11:38 UTC, sofyak0zyreva commented on OcamlBR/lib/ast.ml
добавила

2025-02-14 16:02 UTC, mshipilov5 commented on manytests/.ocamlformat
убрал

2025-02-14 16:40 UTC, Kakadu commented
Там покрытие тестами в требованих >80%...

2025-02-17 20:42 UTC, therain7 requested changes
еще раз
`let f () = y in let y = 42 in f ()` запустите на таком только eval без инфера и посмотрите, что он выдаст

2025-02-18 11:22 UTC, therain7 approved these changes
ok

2025-02-18 11:22 UTC, merged