Add AST of miniML and factorial
Kakadu/fp2024 pull request #6
Opened 2024-09-25 17:52 UTC by IliaSuponeff

Initialize project: `OCaml + polymorphic variants types`. 
Add implementation of `miniML`'s AST on lib/ast.ml. 
Add implementation of factorial function by `miniML`'s AST on bin/REPL.ml.

2024-09-29 14:14 UTC, DronShock commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | UnaryPlus (* ~- *)
Комментарии перепутаны местами

2024-09-29 14:37 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | UnaryPlus (* ~- *)
Благодарю, не заметил, сейчас поправим

2024-09-29 15:21 UTC, Kakadu commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +      expression * statement list * statement list (* if x > 0 then (..) else (..) *)
А из каких соображений If --- statement?

2024-09-29 15:50 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +      expression * statement list * statement list (* if x > 0 then (..) else (..) *)
Никаких, это ошибка, он должен быть в expression type.

2024-09-29 16:55 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +      expression * statement list * statement list (* if x > 0 then (..) else (..) *)
resolved

2024-09-29 17:21 UTC, therain7 requested changes

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/bin/REPL.ml
> +(** Copyright 2021-2024, Ilia Suponev *)
2021?

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/bin/REPL.ml
Это по определению не REPL. Не очень понятно, к чему здесь такое название

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/dune
> +;  (deps ./REPL.exe %{bin:REPL}))
Зачем здесь этот кусок закоменченный? Тем более он энивей появляется в другой директории

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/dune-project
> +(homepage "https://github.com/Kakadu/fp2024")
Может ссылку на свой форк?

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/dune-project
> +  "An interpreter for miniML language similar by OCaml with polymorphic variants types")
```suggestion
  "An interpreter for miniML language similar to OCaml with polymorphic variants types")
```

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/dune-project
> +  angstrom
`angstrom` сейчас нигде не используется в проекте

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +    Valid identifier maths on regex: `[a-zA-Z_][a-zA-Z_0-9]*` or `( [a-zA-Z_][a-zA-Z_0-9]* )`
Это информация не имеет отношения к AST. Можете потом в парсере это уточнить комментом.
После парсинга следующим компонентам интерпретатора должен быть безразличен вид идентификаторов

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | Apply of identifier * expression list (* factorial (n / 2) *)
Когда будете добавлять в AST анонимные функции, поймете, что такое представление `Apply` некорректно.
Попробуйте записать `(fun x -> x) 1`

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +      * statement list (* let [rec] f = (..) *)
Следующее программа не представима:
`fact (let x = 5 in x)`

2024-09-29 17:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | Division (* / *)
Определитесь, вы пишете названия символов или операций:
Plus / Add
Asterisk / Multiply

2024-09-30 08:42 UTC, IliaSuponeff commented on OCamlPolymorphicVariantsTypes/dune-project
> +  angstrom
Принял к сведенью

2024-09-30 09:24 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +      * statement list (* let [rec] f = (..) *)
Это не исправили

2024-09-30 09:25 UTC, therain7 requested changes
Представимо некорректное
`let x = 1 in y = 2`

2024-09-30 09:50 UTC, IliaSuponeff commented
> Представимо некорректное `let x = 1 in y = 2`

А каким образом оно некорректно?
![wtf](https://github.com/user-attachments/assets/baf645e8-4f16-4731-a4b0-5ad05c7ad9ea)

2024-09-30 15:04 UTC, therain7 requested changes
запросите ревью еще раз, когда почините

2024-10-01 05:21 UTC, therain7 requested changes

2024-10-01 05:21 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +[@@deriving show { with_path = false }]
`(let x = 1 in x) + y`
`(let f = fun x -> x in f) 1`
`if (let x = true in x) then print_int 37`

и все подобное не представимо

2024-10-01 17:02 UTC, therain7 requested changes

2024-10-01 17:02 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | StatementItem of statement (* if x > 0 then f x else f (-x);; *)
Как вы собираетесь представлять `let x = 1`?
`DefineItem ("x", Nonrecursive, [Pvar("x")], StatementsBlock([])`?
А если последний список не пустой?

Также, то что вы называете `statement` - на самом деле является `expression` и имеет значение.
Предлагаю не придумывать свои костыли, а посмотреть, как реализовано AST в компиляторе окамла, и отталкиваться от него

2024-10-01 17:02 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | StatementItem of statement (* if x > 0 then f x else f (-x);; *)
Все, что вы определяете в `statement` можно определить в `expression` и не делать этот непонятный лишний тип

2024-10-02 17:36 UTC, Kakadu commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | EpressionBlock of expression list (* (let g x = x / 2 in g y; y); *)
E**x**pression

2024-10-02 17:36 UTC, Kakadu commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | Define of definition * expression (* let <definition> in <expr>*)
?

2024-10-02 17:38 UTC, Kakadu commented
Вы близки к +

2024-10-02 17:48 UTC, therain7 requested changes

2024-10-02 17:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | If of expression * expression * expression (* if x then false else true *)
Не представимо
```ocaml
 if not is_approved then print_endline "kat tak"
```

2024-10-02 17:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +type program = identifier * struct_item list [@@deriving show { with_path = false }]
Что будет первым аргументом? И почему нет коммента, поясняющего это

2024-10-02 17:48 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +[@@deriving show { with_path = false }]
У вас не представимо
`let (a, b) = (1, 2)`

2024-10-05 17:47 UTC, therain7 requested changes
CI почините, будет +

2024-10-05 17:47 UTC, therain7 commented on OCamlPolymorphicVariantsTypes/lib/ast.ml
> +  | EpressionBlock of expression list (* (let g x = x / 2 in g y; y); *)
```suggestion
  | ExpressionBlock of expression list (* (let g x = x / 2 in g y; y); *)
```

2024-10-05 19:26 UTC, therain7 approved these changes
norm

2024-10-05 19:26 UTC, merged