Add AST of interpreter "OCaml + printf" by Rodionov Maxim and Zaikin Vladimir
Kakadu/fp2024 pull request #7
Opened 2024-09-28 13:17 UTC by RodionovMaxim05

- Инициализировали проект "OCaml + printf"
- Добавили реализацию AST в lib/ast.mli
- Добавили пример представления факториала, используя описанные типы, в bin/REPL.ml

2024-09-28 14:01 UTC, Kakadu commented on OCamlPrintf/bin/REPL.ml
> +        (Str_value(
Задумывалось, что дерево будет тайпчекнуто компилятором.

2024-09-29 17:52 UTC, therain7 requested changes

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/bin/REPL.ml
это не REPL по определению

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/dune-project
> +  angstrom
`angstrom` не нужен вам сейчас

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/lib/dune
> + (libraries base angstrom)
Добавьте `base` в `dune-project`, если реально используете

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/lib/ast.ml
> +      - [C P] when [args] is [Some ([], P)] *)
Перечитайте, что вы скопировали

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/lib/ast.ml
> +  | Exp_fun of pattern * expression (** [Exp_fun (P, E)] represents [fun P -> E] *)
Как планируете поддерживать функции нескольких аргументов?

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/lib/ast.ml
> +  | Exp_printf of fstring (** printf "abc %d" 52 *)
А 52 куда пойдет?

2024-09-29 17:52 UTC, therain7 commented on OCamlPrintf/lib/ast.ml
> +  | Exp_printf of fstring (** printf "abc %d" 52 *)
Также это в каком-то роде нарушает `Захардкаживать стандартные функции (а ля print_int) в отдельные виды узлов AST нельзя.` из `tasks.md`

2024-10-01 05:26 UTC, therain7 approved these changes
Мне нрав. Можете мерджится

2024-10-01 05:32 UTC, therain7 commented on OCamlPrintf/lib/ast.ml
> +  | Exp_fun of pattern * expression (** [Exp_fun (P, E)] represents [fun P -> E] *)
Жаль, что не ответили(
Можно было оставить все функции, как функции одного аргумента, а нескольких представлять
`fun x -> fun y -> fun z -> E`

2024-10-01 13:16 UTC, merged